### ISSUE TITLE
Assets are loaded from wrong WebIO install in JuliaBox

### ISSUE THREAD

**Issue by rdeits** [JuliaGizmos/WebIO.jl#100]
When WebIO is built, we do: https://github.com/JuliaGizmos/WebIO.jl/blob/204f58093942f3994c3ebea5b17eb333ededdad6/deps/build.jl#L17

However, JuliaBox actually has two copies of WebIO. There's one installed systemwide in:

```
/home/jrun/.julia/v0.6/WebIO
```

and one installed as part of the user package bundle in:

```
/mnt/juliabox/.julia/v0.6/WebIO
```

*both* of these folders are in `LOAD_PATH`, and the first one is also `Pkg.dir()` at the time that the WebIO plugin is built and installed. 

When you run `using WebIO`, you get the user-package from `/mnt/juliabox`, but when you try to import a javascript asset, WebIO's jupyter extension first looks in the system packages in `/home/jrun`. This results in a weird situation where WebIO's julia and javascript assets can come from different copies of the package (and potentially even different versions). This problem will also occur for any other package which is part of the default JuliaBox systemwide installation.

**Comment by rdeits** [comment]
Yeah, I think matching Julia's priority is totally the right thing to do. We can do that as a general improvement, but I don't know if it will help the situation on JuliaBox because *both* package directories are also in LOAD_PATH when the package is built, and the systemwide one comes first.

**Comment by rdeits** [comment]
This is becoming more of a problem for me in other contexts, and I'm afraid that just changing the preference order isn't going to resolve the situation. The particular problem I'm having is that I do a lot of work in separate Julia environments (with separate package directories and load paths), but WebIO can't pick up assets from anywhere but the default package directory and whatever happened to be on LOAD_PATH whenever it was first installed. 

For an example that doesn't involve JuliaBox at all, imagine: 

1. We install WebIO in the default Julia package directory `~/.julia/v0.6`
2. WebIO installs its jupyter extension to look for assets in `~/.julia/v0.6`
3. We then create a new julia package directory in `/elsewhere` and install some packages into it
4. We run a WebIO app using the julia packages from `/elsewhere` and try to load a `pkg` URL, but we end up getting assets from `~/.julia/v0.6` instead of `/elsewhere`. 

Problems like this seem inevitable given that WebIO is trying to create a single global list of package asset folders. And it seems likely that this will get worse with pkg3, which will make it easier to have nicely separated projects with independent packages. 

The *most* correct place to look is really "wherever the current Julia kernel thinks packages live", but since that can vary by kernel, while we're operating at the notebook server level, that's not really feasible. 

I propose that a more correct implementation would be to at least look "wherever a `julia` process launched with the current environment would think packages live". We could approximate that by reading the `JULIA_PKGDIR` and `JULIA_LOAD_PATH` environment variables, but it's also possible that users will have modified their load path in the julia startup files. We could also try to measure it by launching Julia from within the nbserver extension, but we actually have no way of knowing which `julia` executable we should be calling. 

None of these options are ideal. But I do think that at least using the *current* julia environment, rather than the environment at build time, will be more correct.

**Comment by rdeits** [comment]
closing in favor of the more general #124

**Comment by shashi** [comment]
It seems that on JuliaBox requests to `/pkg/` need to be forwarded to jupyter from the front-facing server which runs juliabox.com
