### ISSUE TITLE
Scopes with imports don't work in Juno or Blink

### ISSUE THREAD

**Issue by rdeits** [JuliaGizmos/WebIO.jl#107]
(split off from #105)

Javascript imports inside Scopes don't load properly in Juno. For example, the `p5.js` demo from the readme fails with:

```
Fetch API cannot load http://cdnjs.cloudflare.com/ajax/libs/p5.js/0.5.11/p5.js. Redirect from 'http://cdnjs.cloudflare.com/ajax/libs/p5.js/0.5.11/p5.js' to 'https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.5.11/p5.js' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://127.0.0.1:3230' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
2plots.coffee [sm]:39 Uncaught (in promise) Error: Failed to fetch
  Instantiating http://cdnjs.cloudflare.com/ajax/libs/p5.js/0.5.11/p5.js
  Loading //cdnjs.cloudflare.com/ajax/libs/p5.js/0.5.11/p5.js
```

`/pkg` imports also fail, but that's not surprising since the Jupyter server isn't there to serve those requests. 

This happens both before and after the systemjs changes in #99

**Comment by rdeits** [comment]
I've checked back to v0.1.4, and I can't find any versions where `examples/p5.jl` works in Blink. I still don't really understand the scope import machinery outside of IJulia, so I'm not sure how helpful I can be here.

**Comment by rdeits** [comment]
Hm. Everything is working now. I can run the p5.js demo app in both Blink and Juno with no issues. 

I wonder if perhaps I was just having intermittent internet access problems when I was testing this?

**Comment by shashi** [comment]
Little known trick: you can call `tools(w)` to open developer tools/js console on blink window `w`.

**Comment by rdeits** [comment]
Cool! I'd just been hacking the `main.js` in Blink.jl to open the dev tools, but that's much nicer.
