### ISSUE TITLE
Getting WebIO working on v0.7

### ISSUE THREAD

**Issue by djsegal** [JuliaGizmos/WebIO.jl#128]
Related to:

+ https://discourse.julialang.org/t/allow-pkg-dir-on-juliabox/9784/5?u=djsegal

-----

<br>

Currently getting the following error from [this line](https://github.com/JuliaGizmos/WebIO.jl/blob/92e58d6401e94edd2d12908fe352e7d800377398/deps/build.jl#L17):

<br>

```julia
WARNING: Broadcast.broadcast_indices is deprecated, use broadcast_axes instead.
  likely near /Users/dan/.julia/packages/Nullables/sjCf/src/nullable.jl:414
WARNING: Base.Pkg is deprecated, run `using Pkg` instead
  likely near /Users/dan/.julia/packages/WebIO/avZI/deps/build.jl:36
WARNING: Base.Pkg is deprecated, run `using Pkg` instead
  likely near /Users/dan/.julia/packages/WebIO/avZI/deps/build.jl:36
┌ Warning: `replace(s::AbstractString, pat, f)` is deprecated, use `replace(s, pat => f)` instead.
│   caller = install_ijulia_config() at build.jl:15
└ @ Main build.jl:15
ERROR: LoadError: MethodError: no method matching dir()
Closest candidates are:
  dir(!Matched::String, !Matched::String...) at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v0.7/Pkg/src/API.jl:403
Stacktrace:
 [1] install_ijulia_config() at /Users/dan/.julia/packages/WebIO/avZI/deps/build.jl:17
 [2] top-level scope
 [3] include at ./boot.jl:314 [inlined]
 [4] include_relative(::Module, ::String) at ./loading.jl:1070
 [5] include(::Module, ::String) at ./sysimg.jl:29
 [6] include(::String) at ./client.jl:390
 [7] top-level scope
in expression starting at /Users/dan/.julia/packages/WebIO/avZI/deps/build.jl:36
```

**Comment by djsegal** [comment]
Related to:

+ https://discourse.julialang.org/t/allow-pkg-dir-on-juliabox/9784/5?u=djsegal

**Comment by rdeits** [comment]
Just ran into this too. I think this problem will fix itself once the new AssetRegistry changes come in, as `Pkg.dir()` won't be as special.

**Comment by djsegal** [comment]
Sounds good.

Also, @stefan suggested we use: `@__DIR__`

**Comment by shashi** [comment]
using AssetRegistry seems to be the only / sane way to locate assets in the face of Pkg3. I'm blocked on doing file locking on windows...

**Comment by togo59** [comment]
Julia v0.7. Cannot build WebIO with Pkg3. I get the same errors with: using AssetRegistry, Pkg and Pkg.build() etc. It would be nice when this is fixed!

**Comment by rdeits** [comment]
@togo59 the relevant blocking issue is https://github.com/JuliaWeb/Mux.jl/pull/64
