### ISSUE TITLE
Rendering observables in jupyter notebook

### ISSUE THREAD

**Issue by piever** [JuliaGizmos/WebIO.jl#133]
So far `Observables` render respectably in Juno (using the "tree view" of Juno), but in the Jupyter notebook they simply print all of their content. Should we render them in the same way as they render when inside a `Node` ?

**Comment by shashi** [comment]
Yeah I think it's ok to add

```
Base.show(io::IO, m::MIME"text/html", w::Observable) = show(io, m, WebIO.render(w))
```
