### ISSUE TITLE
Plans to register package

### ISSUE THREAD

**Issue by djsegal** [JuliaGizmos/WebIO.jl#15]
Is there a reason you're keeping this project unregistered?

**Comment by shashi** [comment]
Will be registering this shortly. I was hoping #5 could get done before registering, but now I'm fine with registering once there's some decent docs... (I did some work on it [here](https://github.com/JuliaGizmos/WebIO.jl/blob/s/docs2/docs/src/index.md))

**Comment by shashi** [comment]
will close this in favor of #42
