### ISSUE TITLE
IJulia no longer works

### ISSUE THREAD

**Issue by cstjean** [JuliaGizmos/WebIO.jl#152]
On OSX, IJulia 1.8.0, Jupyter notebook server 5.4.0, Julia 0.6,

```julia
using WebIO
Node(:div, "Hello, World")
```

returns a blank. I've bisected the problem to this commit: e15615aea95556c0c3db6ab497a95f74d2284c67

**Comment by shashi** [comment]
I think you may have to do `Pkg.build("WebIO")` the Jupyter plugin (in WebIO) has been updated to use AssetRegistry.

**Comment by shashi** [comment]
Thanks for bisecting! If it doesn't work, do paste what's in the JS console. 0.2.3 of WebIO has a fix for Safari, so make sure you're on >=0.2.3 if you're using Safari...

**Comment by cstjean** [comment]
Building and restarting solved it, thank you!
