### ISSUE TITLE
WebIO not defined javascript error

### ISSUE THREAD

**Issue by djsegal** [JuliaGizmos/WebIO.jl#16]
getting the following error after typing:

```
Pkg.build("WebIO")
using WebIO

Node(:div,
      Node(:h1, "Clickbait!", className="title", style=Dict(:color=>"red")),
      Node(:p, "You will not believe what happens when you click this link!", className="description"),
      className="article"
)
```

----------

```
Javascript error adding output!
ReferenceError: WebIO is not defined
See your browser Javascript console for more details.
```

**Comment by JobJob** [comment]
You might need to run:
```
WebIO.devsetup()
WebIO.bundlejs(watch=false)
```
see the README

**Comment by JobJob** [comment]
and/or maybe: `setup_ijulia()`

**Comment by JobJob** [comment]
or `WebIO.setup()`
lots of options 😄  
build/setup is still in flux a little

**Comment by djsegal** [comment]
thanks dood!

**Comment by JobJob** [comment]
So the current situation is you have to run this once, to install deps:
```
WebIO.devsetup()
WebIO.bundlejs(watch=false)
```
then
```
WebIO.setup()
```
after each `using WebIO`?

We'll have to move those to the `build` and `__init__` respectively

**Comment by shashi** [comment]
@JobJob that's correct! :)

I think it's best if we didn't have to keep any glue code that gets loaded in `__init__` it's a source of frequent problems. Instead we should move the glue code to the respective packages and make them depend on WebIO. See #5

**Comment by djsegal** [comment]
It seems dangerous that you have to wait for other people before you can get code into theirs. 

Why not just add glue to this project and then remove it when your PRs get merged? // training wheels style

**Comment by shashi** [comment]
Yeah, I think that's what I'm going to do.
