### ISSUE TITLE
Using Interact inside jupyter lab not working

### ISSUE THREAD

**Issue by meggart** [JuliaGizmos/WebIO.jl#163]
I am trying to use the `@manipulate` macro from the Interact package inside jupyter lab. As I understood from the docs, it should work when the webio labextension bundled with this package is installed. However, in this minimal example:

````julia
using Interact
using WebIO

@manipulate for i=1:10
  i
end
````

I can see a slider and the result, but the number is not updated on slider movement. The same example works without problems in a jupyter notebook. 
I tried to follow all the installation steps from a fresh conda env, I am on Linux, Julia 0.6.2, the jupyter-related package versions are:

````
jupyter_client            5.2.3                    py37_0  
jupyter_core              4.4.0                    py37_0  
jupyterlab                0.32.1                   py37_0  
jupyterlab_launcher       0.11.2                   py37_0  
````

running `jupyter labextension list` gives this:

````
JupyterLab v0.32.1
Known labextensions:
   app dir: /home/fgans/miniconda3/envs/lab/share/jupyter/lab
@jupyter-widgets/jupyterlab-manager
        @jupyter-widgets/jupyterlab-manager v0.35.0  enabled  OK
julia-web-io
        julia-web-io v0.1.0  enabled  OK*

   local extensions:
        julia-web-io: /home/fgans/.julia/v0.6/WebIO/assets/webio
````
In the browser javascript console the following error message is diplayed when the cell is executed:

```
Error: Object 'Signal' not found in registry   default.js:1432
```

Any help would be much appreciated, did I miss some installation steps?

**Comment by shashi** [comment]
Fixed in #199
