### ISSUE TITLE
Add VSCode as a provider

### ISSUE THREAD

**Issue by aaronsheldon** [JuliaGizmos/WebIO.jl#168]
VSCode uses an custom mime type alias of "juliavscode/html" for "text/html" to avoid over capture of terminal output, as described by @davidanthoff in JuliaEditorSupport/julia-vscode#397. I think getting WebIO to work with VSCode will require creating a provider file that maps the MIME support for "juliavscode/html" back to "text/html". However, I haven't figured out the best overloads to use to stitch this together, is it writemime? show? render? display? I think "show" as that should be captured by mimewritable/showable, and hasmethods/methods_exist.

*the provider would also need to detect if the _vscodeserver module was loaded, and load the appropriate javascript into the VSCode pane.

**Comment by travigd** [comment]
@aaronsheldon Are you still interested in this?

**Comment by davidanthoff** [comment]
Just a warning here: I don't think we intend `juliavscode/html` to be a vehicle for complex web UI. I think the main use case we have in mind for it is showing a figure in the plot pane. I probably wouldn't build much more beyond that based on it.

**Comment by travigd** [comment]
I'm going to close this. We're generally not interested in adding new providers to WebIO (in fact we're trying to move things **out** of WebIO and into the appropriate packages).

If someone wanted to do this, I think we'd be happy to support, but it'd probably have to be done in a WebIOVSCode hybrid package which glues them together.
