### ISSUE TITLE
Other events besides click events

### ISSUE THREAD

**Issue by djsegal** [JuliaGizmos/WebIO.jl#17]
Throughout your docs you only talk about click events:

```
  dom"button"(
    "generate random",
    events=Dict("click"=>@js () -> $obs[] = Math.random()),
  )
```

However, I want to do keyboard click events on the actual jupyter cell. 

The only way I can think about doing this in your framework is to have a `onload` function

--------

Do you support `load` events?

**Comment by djsegal** [comment]
I might put some hack together where:

+ I make hidden divs with click events 
+ and then press them using javascript

**Comment by djsegal** [comment]
Also, I end up in this situation where I have a lot of residual scripts inside my jupyter notebooks.

I know it's not really your fault, but its causing the observer to get hit `N` times instead of just one

**Comment by shashi** [comment]
why can't you just use 

```
    events=Dict("keyup"=>@js (event) -> $obs[] = event.key)
```

**Comment by djsegal** [comment]
I don't think that will catch it on a div?

It feels like a lot of the keyboard pressing would have to be handled on the jupyter cell level

**Comment by shashi** [comment]
Ah, if that's the problem, you need `tabindex=1` on the div
```julia
w = Widget()
ob = Observable(w, "keys", 0)
on(println, ob)
w(
    dom"div[tabindex=1]"(style=Dict("height"=>"100px", "width"=>"100px"),
                                     events=Dict("keyup" => @js e -> $ob[] = e.keyCode))
)
```
