### ISSUE TITLE
Error Building WebIO in Julia 1.0.0

### ISSUE THREAD

**Issue by mgiugliano** [JuliaGizmos/WebIO.jl#172]
Building WebIO ────────→ `~/.julia/packages/WebIO/7rrhi/deps/build.log`
┌ Error: Error building `WebIO`:
│ ERROR: LoadError: MethodError: no method matching replace(::String, ::Regex, ::String)
│ Closest candidates are:
│   replace(::String, !Matched::Pair{#s55,B} where B where #s55<:AbstractChar; count) at strings/util.jl:414
│   replace(::String, !Matched::Pair{#s52,B} where B where #s52<:Union{Tuple{Vararg{AbstractChar,N} where N}, Set{#s49} where #s49<:AbstractChar, AbstractArray{#s50,1} where #s50<:AbstractChar}; count) at strings/util.jl:419
│   replace(::String, !Matched::Pair; count) at strings/util.jl:423
│   ...
│ Stacktrace:
│  [1] install_ijulia_config() at /Users/XXX/.julia/packages/WebIO/7rrhi/deps/build.jl:15
│  [2] top-level scope at none:0
│  [3] include at ./boot.jl:317 [inlined]
│  [4] include_relative(::Module, ::String) at ./loading.jl:1038
│  [5] include(::Module, ::String) at ./sysimg.jl:29
│  [6] include(::String) at ./client.jl:388
│  [7] top-level scope at none:0
│ in expression starting at /Users/XXX/.julia/packages/WebIO/7rrhi/deps/build.jl:55
└ @ Pkg.Operations /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.0/Pkg/src/Operations.jl:1068

**Comment by GravityAssisted** [comment]
I can confirm this issue.

**Comment by sandgrules** [comment]
Seeing the same issue - any movement on this?

**Comment by rdeits** [comment]
This will be resolved in https://github.com/JuliaGizmos/WebIO.jl/pull/169
