### ISSUE TITLE
Tag a new release?

### ISSUE THREAD

**Issue by tkoolen** [JuliaGizmos/WebIO.jl#173]
It would be nice to get one more release that supports 0.6 with the `Node` -> `node` changes before https://github.com/JuliaGizmos/WebIO.jl/pull/169. Thanks in advance!

**Comment by piever** [comment]
Agreed, I've just tagged a new one https://github.com/JuliaLang/METADATA.jl/pull/16869

Otherwise it's a mess to update to the new `node` constructor...
