### ISSUE TITLE
still can't build WebIO on Julia 0.7 on Mac

### ISSUE THREAD

**Issue by lewisl** [JuliaGizmos/WebIO.jl#176]
```
Building WebIO ───────────→ `~/.julia/packages/WebIO/RolaR/deps/build.log`
┌ Error: Error building `WebIO`: 
│ WARNING: Base.Pkg is deprecated, run `using Pkg` instead
│   likely near /Users/lewis/.julia/packages/WebIO/RolaR/deps/build.jl:55
│ WARNING: Base.Pkg is deprecated, run `using Pkg` instead
│   likely near /Users/lewis/.julia/packages/WebIO/RolaR/deps/build.jl:55
│ ┌ Warning: `replace(s::AbstractString, pat, f)` is deprecated, use `replace(s, pat => f)` instead.
│ │   caller = install_ijulia_config() at build.jl:15
│ └ @ Main ~/.julia/packages/WebIO/RolaR/deps/build.jl:15
│ ERROR: LoadError: MethodError: no method matching dir()
│ Closest candidates are:
│   dir(!Matched::String, !Matched::AbstractString...) at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v0.7/Pkg/src/API.jl:454
│ Stacktrace:
│  [1] install_ijulia_config() at /Users/lewis/.julia/packages/WebIO/RolaR/deps/build.jl:17
│  [2] top-level scope at none:0
│  [3] include at ./boot.jl:317 [inlined]
│  [4] include_relative(::Module, ::String) at ./loading.jl:1038
│  [5] include(::Module, ::String) at ./sysimg.jl:29
│  [6] include(::String) at ./client.jl:398
│  [7] top-level scope at none:0
│ in expression starting at /Users/lewis/.julia/packages/WebIO/RolaR/deps/build.jl:55
└ @ Pkg.Operations /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v0.7/Pkg/src/Operations.jl:1068
```

Looks like it contains a bunch of deprecations in its build process.

**Comment by rdeits** [comment]
@lewisl thank you for reporting this, but more copies of this issue are not helpful. The problem is resolved, but only in the master branch of WebIO. You need to specifically check out that master branch with `pkg> add WebIO#master` or `pkg> develop WebIO`.

**Comment by lewisl** [comment]
I am pretty confused why I’d get any branch other than master by default.

**Comment by rdeits** [comment]
Please take a look at the manual here: https://docs.julialang.org/en/stable/stdlib/Pkg/#Adding-registered-packages-1

Adding a package gives you the most recent *released version* by default. If you want the master branch, you have to specifically request it.

**Comment by lewisl** [comment]
Tx.

**Comment by lewisl** [comment]
Hmmm….  That makes very clear how to track a specific branch, say master.  But, it doesn’t indicate what branch, if multiple exist, will be downloaded, installed, and updated.  You mentioned “released” but I am not clear on how git makes a given branch “the” release or whether that is part of Pkg’s additional plumbing.

I’d certainly make “master” the default and make people explicitly request some experimental or partially tested branch.

Done for now.
