### ISSUE TITLE
libraries not loading in julia 1.0

### ISSUE THREAD

**Issue by piever** [JuliaGizmos/WebIO.jl#181]
I'm not sure what it is but if I do (on master of Interact, InteractBase, InteractBulma and on https://github.com/JunoLab/Blink.jl/pull/143):

```julia
using Interact, Blink
w = Window()
body!(w, textbox())
```

the `textbox` gets displayed without any style. This is the HTML from the electron console:
```html
<div class="wio-scope">
    <link id="-assetserver-afdc6ddab415532b9a9d613beefe7fde0841edc5-style.css" rel="stylesheet" type="text/css" href="/assetserver/afdc6ddab415532b9a9d613beefe7fde0841edc5-style.css" media="all">
    <link id="-assetserver-6077c508af812776704ea53e93bbf17354358a62-bulma.min.css" rel="stylesheet" type="text/css" href="/assetserver/6077c508af812776704ea53e93bbf17354358a62-bulma.min.css" media="all">
    <link id="-assetserver-666214600090acdf45c04485fc0cf41a913def8a-bulma-slider.min.css" rel="stylesheet" type="text/css" href="/assetserver/666214600090acdf45c04485fc0cf41a913def8a-bulma-slider.min.css" media="all">
    <link id="-assetserver-c2ddbd100f667cd72a3a0f051e0229103e5eb2ee-bulma-switch.min.css" rel="stylesheet" type="text/css" href="/assetserver/c2ddbd100f667cd72a3a0f051e0229103e5eb2ee-bulma-switch.min.css" media="all">
    <link id="-assetserver-881760eb4069a77e68f0b3638eae380b6f03cf20-bulma-accordion.min.css" rel="stylesheet" type="text/css" href="/assetserver/881760eb4069a77e68f0b3638eae380b6f03cf20-bulma-accordion.min.css" media="all">
    <link id="-assetserver-b2a50f779e75cff96d88baca04a1832806f9994f-bulma-checkradio.min.css" rel="stylesheet" type="text/css" href="/assetserver/b2a50f779e75cff96d88baca04a1832806f9994f-bulma-checkradio.min.css" media="all">
    <link id="-assetserver-9101c3c3a0853b487201a2498ca4022598ef6d40-bulma-tooltip.min.css" rel="stylesheet" type="text/css" href="/assetserver/9101c3c3a0853b487201a2498ca4022598ef6d40-bulma-tooltip.min.css" media="all">
    <input type="text" data-bind="value: value, valueUpdate: 'input', event: {change : function () {this.changes(this.changes()+1)}}" placeholder="" class="input ">
</div>
```

So it looks like the libraries are there but somehow don't seem to be effective...

Same in Mux, whereas in the Jupyter notebook the correct styling is applied. Any idea what it could be?

**Comment by rdeits** [comment]
Are the asset server URLs working? You can do `tools(w)` and then use the inspector. I think you should be able to right-click on the `href` attribute and do "Open in debugger".

**Comment by rdeits** [comment]
The blink devtools console is full of warnings like: `Resource interpreted as Stylesheet but transferred with MIME type application/octet-stream: "http://127.0.0.1:2068/assetserver/2adf2d3c0a309d161defee389ef9f4745309593d-bulma-tooltip.min.css".` which seems like it might be relevant.

**Comment by rdeits** [comment]
fixed in https://github.com/JuliaWeb/Mux.jl/pull/68

**Comment by rdeits** [comment]
@piever can you check if this is indeed fixed with Mux.jl master? If so, we can tag a new Mux release.

**Comment by piever** [comment]
Yes , I've been using your PR locally for a few days and it works beautifully, we should definitely tag a release!

**Comment by rdeits** [comment]
https://github.com/JuliaLang/METADATA.jl/pull/17229
