### ISSUE TITLE
Do not hijack the REPL with webio_serve

### ISSUE THREAD

**Issue by piever** [JuliaGizmos/WebIO.jl#184]
When doing `webio_serve` now the REPL is "hijacked" by the HTTP listener. This is often not desired though as it makes it impossible to keep working at the REPL to investigate the value of the `Widgets` and `Observables` in the app. I assume it should be possible, as the same operation in Blink leaves the REPL available.

**Comment by aaronsheldon** [comment]
To address a similar problem with plot rendering hijacking `print` and `show` in VSCode @davidanthoff in JuliaEditorSupport/julia-vscode#397 had to create a custom mime type.

**Comment by piever** [comment]
This is fixed in latest Mux.
