### ISSUE TITLE
WebIO rendering into a Juno plot pane broken

### ISSUE THREAD

**Issue by ajkeller34** [JuliaGizmos/WebIO.jl#188]
Changes in Juno have caused WebIO’s rendering into the plot pane to fail. Ref: https://github.com/JunoLab/Atom.jl/issues/128

**Comment by Roboneet** [comment]
Doing
```julia 
]add Atom#master
]build Atom
```
and restarting Julia terminal fixed it for me

**Comment by travigd** [comment]
Rendering in Juno works for me™ and this issue is quite old, so I'm closing this. Feel free to reach out if this is still broken for you.
