### ISSUE TITLE
Give a "clean" HTML representation of Node

### ISSUE THREAD

**Issue by vdayanand** [JuliaGizmos/WebIO.jl#190]
Is there a way to convert WebIO.Node to html string?

WebIO.htmlstring doesnt give a clean output: 
`WebIO.htmlstring(node(:h1, "Hello"))`
gives 
`"<div class='display:none'></div><unsafe-script style='display:none'>\nWebIO.mount(this.previousSibling,{&quot;props&quot;:{},&quot;nodeType&quot;:&quot;DOM&quot;,&quot;type&quot;:&quot;node&quot;,&quot;instanceArgs&quot;:{&quot;namespace&quot;:&quot;html&quot;,&quot;tag&quot;:&quot;h1&quot;},&quot;children&quot;:[&quot;Hello&quot;]})</unsafe-script>"
`

**Comment by travigd** [comment]
Closing as stale.
