### ISSUE TITLE
Tests mysteriously failing

### ISSUE THREAD

**Issue by rdeits** [JuliaGizmos/WebIO.jl#193]
The tests have started mysteriously failing: 

```
global URL, no http:: Test Failed at /home/rdeits/.julia/dev/WebIO/test/blink-tests.jl:92
  Expression: scope_import(w, "//people.csail.mit.edu/rdeits/webio_tests/trivial_import.js", use_iframe) == "ok"
   Evaluated: nothing == "ok"
Stacktrace:
 [1] top-level scope at /home/rdeits/.julia/dev/WebIO/test/blink-tests.jl:61
```

I'm pretty sure it's not anything we changed, and that URL is still valid. I'll see if I can figure out what's going on.

**Comment by rdeits** [comment]
Actually it looks like a16d21835075eeea2245ccd7b85da91dc27841e2 is the problem. @shashi did you mean to commit that directly to master?

**Comment by shashi** [comment]
I pushed it by mistake, sorry! This is a case I guess we should handle too.

**Comment by shashi** [comment]
(I'm making a PR to fix this)
