### ISSUE TITLE
Node objects are not rendered in notebook

### ISSUE THREAD

**Issue by vdayanand** [JuliaGizmos/WebIO.jl#195]
![image](https://user-images.githubusercontent.com/31879758/45288213-c50a8680-b507-11e8-8222-10fd3702b451.png)

**Comment by rdeits** [comment]
Thanks for reporting this. Do you see any errors in the javascript console? (developer tools -> web console in your browser)

**Comment by vdayanand** [comment]
It seems to work now for me :)

**Comment by rdeits** [comment]
Ok, then I'm going to close this. If you can reproduce the issue please feel free to re-open it.
