### ISSUE TITLE
Unable to import JS libs compiled with emscripten

### ISSUE THREAD

**Issue by chfin** [JuliaGizmos/WebIO.jl#213]
I ran into an issue while trying add https://www.verovio.org/javascript/develop/verovio-toolkit.js as a scope import. Apparently, this lib attempts to also load the paths `/fs`, `/path`, and `/crypto`, which are not served by WebIO. As a result, code registered with `onimport` is not executed.

This doesn't work:
```julia
using WebIO, JSExpr
function test()
    w = Scope(imports=["https://www.verovio.org/javascript/develop/verovio-toolkit.js"])
    onimport(w, @js function (v)
        console.log("test"); # <<< This won't show up
    end)
    w(dom"div"())
end
```

while this does work:

```julia
using WebIO, JSExpr
function test()
    w = Scope()
    onimport(w, @js function (v)
        console.log("test"); # <<< This does show up
    end)
    w(dom"div"())
end
```

The files mentioned above are not requested when including the JS library in a script tag in a simple html page. Also, this seems to be related to the lib being compiled with emscripten, as I tried to load another emscripten-compiled library (//cdn.rawgit.com/fta2012/ccv-js/f63c56c8/build/ccv.js) and got the same behaviour. This was tested by serving with Mux
```julia
WebIO.webio_serve(page("/", req -> test()))
```
The served page was tested in Firefox and Chrome, who both report that `/fs` and the like are requested from bundle.js.

**Comment by shashi** [comment]
Do you see anything in the browser's JS console?

**Comment by chfin** [comment]
In Firefox, the only output by default is `defining unsafe-script`. If I enable requests and XHRs on the console, I can see requests for
- `bundle.js`,
- `mux_setup.js`,
- `webcomponents-lite.min.js`, and
- `/webio-socket`,

then `defining unsafe-script` followed by XHRs to
- `https://www.verovio.org/javascript/develop/verovio-toolkit.js` (successful),
- `localhost:8000/fs`,
- `localhost:8000/path`, and
- `localhost:8000/crypto` (all 404).

In Chromium, I get similar results but additionally
```
Uncaught (in promise) Error: Fetch error: 404 Not Found
  Instantiating http://localhost:8000/fs
  Loading https://www.verovio.org/javascript/develop/verovio-toolkit.js
  Loading https://www.verovio.org/javascript/develop/verovio-toolkit.js
    at bundle.js:2609

t			@	bundle.js:2609
(anonymous)		@	bundle.js:2609
Promise.then (async)		
createScope		@	bundle.js:2948
createNode		@	bundle.js:145
mount			@	bundle.js:189
(anonymous)		@	VM54:2
(anonymous)		@	bundle.js:3054
evalInContext		@	bundle.js:3054
connectedCallback	@	bundle.js:3064
setup			@	bundle.js:3068
(anonymous)		@	bundle.js:3098
```

**Comment by travigd** [comment]
2¢: fs, path, and crypto are built-in modules when using NodeJS. I looked briefly at the bundle code and I think it tries to determine what JS environment it's running under (browser vs node vs webworker) but I think (?) it might be failing because Jupyter notebook defines `require` which is how imports are done using Node.

So the module thinks it's running under NodeJS and thus tries to access modules that are only available under NodeJS. The "fix" if I'm correct would be to fix the heuristic for determining if running under Node. The hack would be removing and then re-setting require before and after the script is imported.

```js
_require = window.require;
window.require = undefined;
// import module
window.require = _require;
```

**Comment by chfin** [comment]
Note that this error also occurs when the scope is just served using `webio_serve`, i.e. not inside a notebook. So this seems to be unrelated to Jupyter.

**Comment by travigd** [comment]
See https://github.com/systemjs/builder/issues/261.

SystemJS defines `process` which makes the emscripten-built-module think it's running under NodeJS and thus try to import those modules. This worked for me.
```julia
w = Scope(
    imports=["https://www.verovio.org/javascript/develop/verovio-toolkit.js"],
    systemjs_options=Dict(
        "meta" => Dict(
            "https://www.verovio.org/javascript/develop/verovio-toolkit.js" => Dict(
                "format" => "global",
            ),
        ),
    ),
)
```

**Comment by chfin** [comment]
This seems to work, great! Thanks a lot!
