### ISSUE TITLE
Remote procedure calls in WebIO

### ISSUE THREAD

**Issue by piever** [JuliaGizmos/WebIO.jl#216]
There was some conversation on slack on implementing generic RPC's in WebIO (meaning, from javascript to call Julia, wait for the result  and then do something with it). I'm copying it here as the idea is interesting and things always risk getting lost on slack.

The proposed syntaxes by @travigd is:

```julia
myrpc = WebIO.RPC(myfunction)
```
 and then 
```julia
js"async function (x) { let result = await $rpc(x); /* other stuff here */ }"
```

**Comment by travigd** [comment]
Maybe we can also generalize this to "local procedure calls" (so to speak).

```julia
addFunc = WebIO.Func(js"""
function add(x, y) {
  return x + y;
}
"""
```
and then
```julia
js"myVal = await $addFunc(3, 4);
```

Keeping it await-based would avoid some issues about when to transfer function bodies to the JS side (e.g. when do we send the body of `addFunc` to the browser?). Only downside is that async isn't globally supported but IS [supported by all recent browsers](https://caniuse.com/#feat=async-functions). We could also (in the _distant_ future) add a babel transpilation plugin.

This could also make for an extensible way for other libraries to provide WebIO functionality.

**Comment by shashi** [comment]
I'd just like to add that we can simply use Conditions to have the `jseval` function that executes some JS in a Scope and waits till a result is returned (if the result is a Promise then waits on the promise resolution and returns the promised value). It would look something like:

```julia
jseval(scope, @js ...)
```
Of course this is just the Julia side of the API.

**Comment by shashi** [comment]
Just remembered we already have `evaljs` which does not wait, but we can I guess add `evaljs_sync`. Also this has been there in Blink for a long time `@js` -- sync and `@js_` -- async.

**Comment by shashi** [comment]
```js"async function (x) { let result = await $rpc(x); /* other stuff here */ }"
