### ISSUE TITLE
Compatibility issues with WebIO 0.4.1

### ISSUE THREAD

**Issue by rdeits** [JuliaGizmos/WebIO.jl#219]
Hey all, I'm sorry I don't have time to dig into what exactly is going on, but I've noticed that MeshCat is totally broken on WebIO 0.4.1, while it works fine with 0.4.0. It's easy to test by just installing MeshCat and running: 

```
julia> using MeshCat

julia> open(Visualizer())
```

With WebIO v0.4.0, this will open a new browser tab with an empty 3D world (after a couple seconds). But with WebIO v0.4.1, the tab is just blank forever. It looks like the Julia server is probably never responding to the browser's request for the page content. 

Anyway, I'll try to debug this more if I have time, but I wanted to let you all know right away.

**Comment by shashi** [comment]
I can reproduce this, but still looking for clues to see what's going on.

**Comment by shashi** [comment]
```
$ telnet 127.0.0.1 8700
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.
GET / HTTP/1.1
Host: 127.0.0.1



```
Well the server doesn't respond to the first request itself.

**Comment by shashi** [comment]
reverting https://github.com/JuliaGizmos/WebIO.jl/pull/206 makes the problem go away cc @SimonDanisch 

Note that this may have something to do with the fact that tasks that are not waited on no more print an error and fail silently.

**Comment by shashi** [comment]
I tried with this patch but nothing gets printed:
```julia
diff --git a/src/servers.jl b/src/servers.jl
index a36c0d3..04f8753 100644
--- a/src/servers.jl
+++ b/src/servers.jl
@@ -7,7 +7,16 @@ end
 Base.open(vis::Visualizer, args...; kw...) = open(vis.core, args...; kw...)
 
 function Base.open(core::CoreVisualizer, port::Integer)
-    @async WebIO.webio_serve(Mux.page("/", req -> core.scope), port)
+    @async begin
+        try
+            WebIO.webio_serve(Mux.page("/", req -> core.scope), port)
+        catch err
+            bt = catch_backtrace()
+            Base.showerror(stderr, err)
+            Base.show_backtrace(stderr, bt)
+            rethrow(err)
+        end
+    end
     url = "http://127.0.0.1:$port"
     Compat.@info("Serving MeshCat visualizer at $url")
     open_url(url)
@@ -20,7 +29,7 @@ function open_url(url)
         elseif Compat.Sys.isapple()
             run(`open $url`)
         elseif Compat.Sys.islinux()
-            run(`xdg-open $url`)
+            #run(`xdg-open $url`)
         end
     catch e
         println("Could not open browser automatically: $e")

```

A good thing to check would be to load the viz code in a notebook and see if it throws (that should invoke the suspect import.jl code paths). Or else the last resort is to stare at Simon's patch and/or write tests for it.

**Comment by SimonDanisch** [comment]
But I can verify, that checking out exactly one commit before https://github.com/JuliaGizmos/WebIO.jl/commit/fef1012b429a501649dbff27d5515de6f62a9c83 works, while https://github.com/JuliaGizmos/WebIO.jl/commit/fef1012b429a501649dbff27d5515de6f62a9c83 doesn't work....

**Comment by pfitzseb** [comment]
I think I actually ran into this yesterday as well -- I was trying to use `AssetRegistry` to register a local file  and then thought it would be a good idea to use the `key` returned by `AssetRegistry.register` instead of the file path. Imho that's a valid thing to do.

**Comment by SimonDanisch** [comment]
Yeah, but then we should specifically check with assetregistry, so that we're still able to throw (a surpressed :P) error when a file isn't found ;)

**Comment by pfitzseb** [comment]
Right, so just add a 
```
elseif path in keys(AssetRegsitry.registry)
  return path
```
?

**Comment by SimonDanisch** [comment]
yeah why not... could add a `startswith("/assetpath/", ...)` to also allow the relative url part

**Comment by shashi** [comment]
Well it seems like disallowing automatic register may be saner at this point then? We can do that.

**Comment by shashi** [comment]
> Maaaaan, can we at some point really make sure that HTTP + Mux etc don't just sent all errors to nirvanna?! 

That diff was our best hope...

**Comment by SimonDanisch** [comment]
we could do a bit better with the generic_http provider I think... Maybe I should add a serve function to it, and add the right try catches^^

**Comment by pfitzseb** [comment]
Things should also get better after we update to the new HTTP.jl, right?
