### ISSUE TITLE
Dependencies Rework (RFC/Proposal)

### ISSUE THREAD

**Issue by travigd** [JuliaGizmos/WebIO.jl#229]
This originated in the Gizmos slack. We were talking about altering (or even getting rid of) "scopes" since they don't seem to be a rigidly defined concept. We could replace everything with DOM and Observable nodes. This would require reworking dependencies/imports though.

## Proposal
I proposed something like the following, together with an `onmount` function that works for any node.
```julia
my_div = dom"div"("Loading...")
mydep = WebIO.Dependency("https://.../my-cool-library.js")
onmount(my_div,
    js"""
    async function() {
        const mydep = await $mydep;
        mydep.someFunction();
    }
    """)
```

I also suggested having support for automatically downloading NPM modules. This wouldn't require NPM itself since (I believe?) the modules are downloaded as tarballs. This could be (should be?) made into another package.

```julia
using WebIONPM
React, ReactDOM = NPMDependency.(["react@^16.6.0", "react-dom@next"])
myjs = js"""
async function() {
    const [React, ReactDOM] = await Promise.all([$React, $ReactDOM]);
    // Etc etc etc
}
"""
```

## JSExpr.jl
Finally, I'm not sure how this would integrate into JSExpr. We could steal the await syntax again I suppose (just generally integrate `@await` into JSExpr for any asynchronous function).

```julia
onmount(my_div) do
    @var React = @await $React
    @var ReactDOM = @await $ReactDOM
    # ...
end
```

Another syntax might by using a RequireJS style API.
```julia
onmount(my_div, @require [React, ReactDOM] do React, ReactDOM
    ReactDOM.mount(...)
end)
```
But this seems noisy.

## Async Support
`await` isn't supported by every browser, but [it supported by all of the latest browsers](https://caniuse.com/#feat=async-functions) (>85% overall). Given that we're targeting a more technical audience, I think this might be okay.

## Async Ordering
Asynchronous code can be harder to manage and cause race conditions, especially with `onmount` and parent/child relationships. Currently, _I believe that_ child `onimport` calls are completed before the parent `onimport`.
We could either say "good luck, you're on your own" with regards to this ordering or we could guarantee some execution ordering (e.g. we wait for children `onmount`'s to finish before triggering the parent `onmount`). We could also do an `await this.promises.childrenMounted` type thing.
I think the best thing to do would be to have an `onmount` function that takes a `wait_for_children` type argument (which defaults to true).
```julia
# These would be equivalent
onimport(my_div, js"""
    async function(node) {
        await node.promises.children;
        console.log(node.dom.children);
    }
""")

onimport(my_div, js"""
    function() {
        console.log(this.children);
    }
""", wait_for_children=true)

**Comment by travigd** [comment]
Ping @shashi @SimonDanisch @pfitzseb 

Feedback welcome (very much appreciated -- even just "looks good" or "wtf"). Is possibly removing `Scope` as a concept something we would want to consider? I think this proposal could exist either way (though removing `Scope` would require this - or something equivalent for managing imports).

**Comment by travigd** [comment]
Oops - note on the last one - I think wait_for_children (maybe a better name too) should be true by default as I think that would be the least surprising behavior.

**Comment by shashi** [comment]
I like the thorough thinking here.

> Is possibly removing Scope as a concept something we would want to consider? 

I believe but cannot prove that it makes life easier to have the concept of DOM separated from the concept of a "Component" (which is what Scope with all its undefined meaning provides).

The features provided by this convenience are:

1. You can store things in `this` inside `onimport` where `this` is a client-side mirror image of a "component". so I can say `this.p5canvas =   @new p5(f, "p5container");`
2. Observables are associated with a scope (this needs to be better defined when an observable is used in multiple places though), so you can access the mirror image `this.p5canvas` in a handler for the observable (i.e. in `onjs` [example](https://github.com/sglyon/PlotlyJS.jl/blob/master/src/display.jl#L59)). It's not obvious what would substitute this in your proposal.
3. Scope acts as a dictionary for observables, allowing a nice abstraction where a scope is a jigsaw piece that fits with other pieces if you connect up the right bumps and holes (signals and slots) [an example here](https://github.com/sglyon/PlotlyJS.jl/blob/master/src/display.jl#L33-L45). I guess in your proposal, the setup will be like the whole page is a breadboard, it's different, but still good.


> since they don't seem to be a rigidly defined concept. 

If we don't find a satisfying alternative to point 2). We can also take the path of defining Scope more clearly.

As for the syntax proposals, I hate this one the most:
```
onmount(my_div, @require [React, ReactDOM] do React, ReactDOM
    ReactDOM.mount(...)
end)
```
we can even do the following
```
onmount(my_div, Dependency("react"), Dependency("Blah"), @js function (React, ReactDOM)
    ReactDOM.mount(...)
end)
```
 or `imports=[]` kwarg from Scope can be moved to `onmount`.

Also have you looked at the Sync and Async types in import.jl ? they allow you to create a DAG of dependencies (e.g. Jquery UI must be loaded after Jquery, but moment.js can be loaded independently)

waiting on children sounds good. the kwarg would be a good bonus.

**Comment by travigd** [comment]
To clarify,

```julia
React = WebIO.JSDependency("./path/to/react.js")
js"""async function() {
    const React = await $React;
    // ...
}
```

would be converted to

```js
async function() {
    const React = await WebIO.loadDependency("/assets/whatever/react.js");
    // ...
}
```
where the path given to `loadDependency` depends on where the file was registered to the asset registry.

**Comment by shashi** [comment]
:+1:

**Comment by travigd** [comment]
I'm not sure where we left off on this.

I think I'd like to
* Leave scope as a concept
* Remove `Scope.imports`
* Rename `onimport` to `onmount`

Is that okay? (@shashi)

**Comment by shashi** [comment]
I guess https://github.com/JuliaGizmos/WebIO.jl/issues/230#issuecomment-440460137 this is the latest.

The steps mentioned seem ok to me.

**Comment by travigd** [comment]
I've begun doing this. Check out [this commit](https://github.com/JuliaGizmos/WebIO.jl/commit/47e05af9a61485bdf5a79808a446e0fc9491f191) for the base.

* Added `onmount`
* `Scope(imports=[...])` now yields a deprecation warning (but still works)
* `onimport` is essentially a shim (with a deprecation warning) around `onmount`

The following code is now more more idomatic (and works!) under this design.
```julia
MyLibrary = JSAsset("https://cdn.whatever/library.js")
w = Scope()
onmount(w, js"""
    async function() {
        const MyLibrary = await $MyLibrary;
        MyLibrary.doTheThing();
    }
    """)
w(dom"div"("hello!"))
```

**Comment by travigd** [comment]
This mostly works now, though we un-deprecated the imports keyword to allow for easy imports of (e.g.) CSS.
