### ISSUE TITLE
Not working on Jupyter with Interact example

### ISSUE THREAD

**Issue by juliohm** [JuliaGizmos/WebIO.jl#237]
Hello,

The snippet of code below is not updating in Jupyter, but it is updating correctly in other places such as when I use Blink:

```julia
using Interact

@manipulate for i in 1:5
  i
end
```

@piever told me that this might be an issue with WebIO.jl. Please let me know what I can do to help fix it. Below is my version information:

```
Julia Version 1.0.0
Commit 5d4eaca0c9 (2018-08-08 20:58 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, skylake)

WebIO v0.6.1
```

**Comment by rdeits** [comment]
Yeah, guys, this seems to be another thing that broke with the 0.6 release :-/

@juliohm I just encountered the same issue. Running `pkg> pin WebIO@0.4.2` and restarting juypter was enough to get basic `@manipulate` usage working again.

**Comment by travigd** [comment]
I can reproduce this. It's very strange that it's working with Blink but not Jupyter...

**Comment by travigd** [comment]
Additionally, refreshing seems to fix things. Doing anything after you've refreshed the page after initially loaded Interact/IJulia seems to make things work.

**Comment by travigd** [comment]
Opening the notebook in a new tab and updating the slider will also make the slider start working in the original tab. This is mildly maddening.

**Comment by juliohm** [comment]
Thank you @rdeits I confirm that pinning the version to 0.4.2 serves as a temporary workaround.

**Comment by juliohm** [comment]
Works nicely @travigd , thank you for taking care of it :100:

**Comment by travigd** [comment]
Glad to help. :sunglasses:
