### ISSUE TITLE
webio_serve and @app doesn't work

### ISSUE THREAD

**Issue by leo60228** [JuliaGizmos/WebIO.jl#241]
Any request made using `webio_serve` and `@app` times out. The same code with `Mux.stack` works.

**Comment by stefan911** [comment]
I can't get any routing other than to "/" to work:

app = Mux.stack(page("/failhttp", req -> respond("fail")),  
                    page("/", req -> itworks()),
                    page("/failws", req -> nope()))
WebIO.webio_serve(app, 8088)

appending /webio-socket to routes  vs not appending seems to be the issue:
/webio-socket vs /failws/webio-socketin my case

**Comment by stefan911** [comment]
Digging deeper :src/providers/mux.jl  is appending the "webio-socket" string removing this from the websocket routing allows routing to work.

 websock = Mux.App(Mux.mux(
        Mux.wdefaults,
        Mux.route("/", create_socket),  #"/webio-socket" only seems to work at root
        Mux.wclose,
        Mux.notfound(),
    ))

**Comment by cstjean** [comment]
@stefan911 Make a PR! It would be great to have a fix for this issue.

**Comment by shashi** [comment]
Thanks @cstjean for #379
