### ISSUE TITLE
[RFC] HTTP.jl v0.8.0

### ISSUE THREAD

**Issue by EricForgy** [JuliaGizmos/WebIO.jl#248]
Hi 👋 

I have a package that depends on both HTTP.jl v0.8.0 and PlotlyJS.jl. 

PlotlyJS.jl depends on WebIO.jl.

WebIO.jl depends on WebSockets.jl.

WebSockets.jl depends on HTTP.jl and currently caps the HTTP.jl version to v0.7.99. 

This means that any package that depends on HTTP.jl v0.8.0 cannot have a dependency on WebIO.jl (inlcuding PlotlyJS.jl). So my package is currently broken.

WebSockets.jl is close to being able to support HTTP.jl v0.8.0, but that will be a breaking change and will impact WebIO.jl.

I'd like to start working on WebIO.jl to prepare it for compatibility with HTTP.jl v0.8.0 (so my package will work again 🙏 ).

I see two paths forward and would like to hear your thoughts before I start work.

One of the paths would be to update WebIO.jl so it uses the coming updated WebSockets.jl that supports HTTP.jl v0.8.0.

Another path would be to update WebIO.jl so that it uses the HTTP.WebSockets.jl already embedded in and working with HTTP.jl v0.8.0.

Do you have any preference?

**Comment by travigd** [comment]
@SimonDanisch You know about this stuff, right?

**Comment by SimonDanisch** [comment]
uh, I guess?! :D  
I wanted to wait untill WebIO stabilizes though, before looking into such things ;)
