### ISSUE TITLE
Fix double loading of assets in `onimport`

### ISSUE THREAD

**Issue by shashi** [JuliaGizmos/WebIO.jl#255]
#242 has a subtle redundancy: rendering a Scope loads imports, but calling `onimport` asks it to load it again (although SystemJS may reuse the previously loaded js files.).

We should probably not call SystemJS twice.

**Comment by travigd** [comment]
I did it purposefully because SystemJS does cache the result and implementing a check in WebIO would be redundant.

**Comment by travigd** [comment]
@shashi Are you okay with the status quo on this? SystemJS de-dups things already.

**Comment by shashi** [comment]
I think we should leave this issue open, so that one day it can be resolved.

**Comment by travigd** [comment]
I don't think it's an issue at all, especially since other modules can `require` things and have it be loaded by SystemJS.

**Comment by travigd** [comment]
I'm going to close this for housekeeping. I don't think it's any worse than `using XYZ` twice in two different files.
