### ISSUE TITLE
MeshCat related issues

### ISSUE THREAD

**Issue by shashi** [JuliaGizmos/WebIO.jl#261]
Found one so far

- [ ] `MethodError: no method matching onimport(::WebIO.Node{WebIO.IFrame}, ::WebIO.JSString)`

**Comment by travigd** [comment]
How did you cause this to occur? In general, one should use `onimport` on the scopes, not IFrames (since IFrames don't have all of the machinery that scopes do).

**Comment by travigd** [comment]
Fixed by (pending merge) #266, https://github.com/rdeits/MeshCat.jl/pull/99, and https://github.com/rdeits/MeshCat.jl/pull/100.
