### ISSUE TITLE
Building should run bundling script if dist files differ.

### ISSUE THREAD

**Issue by travigd** [JuliaGizmos/WebIO.jl#264]
@shashi And I discussed and agreed on only committing the built JavaScript files for releases (to avoid a messy git history).

However, it'd be nice if we could detect that a user was installing WebIO since the last time the files were committed (e.g. installing from `WebIO#master`) and (at least try to) run the `bundlejs` script.

Currently, one would have to `Pkg.test` WebIO to have the new JavaScript built (the bundle script is run before any tests run), which is an _okay_ workaround.

**Comment by shashi** [comment]
I guess we should use make or npm itself to detect and run?

**Comment by travigd** [comment]
We could just try to detect the presence of npm and always build if it's available? Another way might just be a heuristic that says "has there been a commit since the last release? if so, build."
