### ISSUE TITLE
deps/build.jl creates %APPDATA% folder in my home directory on Windows

### ISSUE THREAD

**Issue by alkorang** [JuliaGizmos/WebIO.jl#279]
![image](https://user-images.githubusercontent.com/11420879/56961341-8278e580-6b8e-11e9-971d-7983fe20d98c.png)
540848e55c47eb13a189b085f2994ed6694b8727
Maybe use `joinpath(ENV["%APPDATA%"], "jupyter")` instead?

Edit: No, `EVN["APPDATA"]` without `%`

**Comment by travigd** [comment]
We should use IJulia's method of discovering APPDATA since it _works_.
https://github.com/JuliaLang/IJulia.jl/blob/master/deps/kspec.jl

**Comment by travigd** [comment]
We should probably just make IJulia a hard dependency (as opposed to the "soft" dependencies like Blink and Mux) and use their implementation of `jupyter_data_dir()`.

**Comment by shashi** [comment]
That would be bad for apps that just want to use Blink (@ranjanan has one)

**Comment by travigd** [comment]
How about just checking if IJulia is installed in the build process and only installing the extension then? The trade-off is that if IJulia was installed later, the extension wouldn't be installed, but we could move the installation process into a function so people could call `WebIO.install_nbextension()` (and include that bit of help in the `WebIO not detected` message, or link to maybe a section of the readme with troubleshooting information).

How does that sound?

**Comment by pfitzseb** [comment]
We could also check via Requires if IJulia and WebIO are loaded in the same Julia process, no? And only install the nbextension if that's the case.

**Comment by travigd** [comment]
Yes but I don't think trying to install the extension every time WebIO is loaded is the best thing to do. For example if someone (for some reason) wanted to remove the extension we shouldn't force them to install it every time. Also, in the case of the notebook, it won't work since the JavaScript wouldn't be loaded until refresh anyway.

**Comment by travigd** [comment]
Closed by #286.
