### ISSUE TITLE
Scope.id deprecated.

### ISSUE THREAD

**Issue by DhruvaSambrani** [JuliaGizmos/WebIO.jl#311]
## The bug

Refer to [this](https://github.com/sglyon/PlotlyJS.jl/issues/283#issue-453613753) issue in PlotlyJS.jl

**Comment by travigd** [comment]
This is not a bug and is working as intended. PlotlyJS should migrate away from use of manually specified scope ids.

**Comment by DhruvaSambrani** [comment]
So it's a PlotlyJS issue?
Cool, I'll close this
