### ISSUE TITLE
JavaScript Package Management

### ISSUE THREAD

**Issue by travigd** [JuliaGizmos/WebIO.jl#313]
Currently, we include "compiled" (_i.e._ transpiled and/or bundled) JavaScript in this repository. It's not ideal.

## What do we do now?
Currently (this hasn't been super consistent), we've discussed `.gitignore`ing the generated files and force-adding them whenever we do a release. This is to avoid having lots of PRs that change these files (it also avoids the possibility of merge conflicts).

#### Why do we do this?
Because we don't want to make people install Node and NPM on their own machines in order to build the JavaScript themselves.

#### What are the issues?
We're still including many relatively large files in our git history which makes the repository larger (and slower to download). Also, it's not very _ergonomic).

## What should we do instead?
I'd like to set up a CI script that will run whenever a new version of WebIO is tagged (this happens automagically with TagBot when we update the version and register with the General metadata repo). The CI pipeline would generate the transpiled/bundled stuff and upload to NPM (and/or GitHub release assets) and the build step of installing WebIO would download these files (by reading the version of WebIO in Project.toml or something similar).

#### Pros
* No more dealing with generated JS in the codebase.
* Simplifies JupyterLab extension (simply run `jupyter labextension install @webio/jupyter-lab-provider` to get it for the corresponding version of WebIO).

#### Cons
* We depend on a third-party solution (NPM). I don't think this is a big deal since NPM is relatively reliable and we basically already do.

**Comment by SimonDanisch** [comment]
Could we upload it to npm AND as release artifacts, so that a normal build can just download them from github?
