### ISSUE TITLE
Don't silently install things into other software systems

### ISSUE THREAD

**Issue by davidanthoff** [JuliaGizmos/WebIO.jl#314]
I installed the Juno integration for Atom the other day. And now, all of a sudden, I'm getting messages inside jupyterlab that I need to rebuild webio.

I generally think this is really not ideal: if I install something like Juno, the last thing I want to happen is that some package down in the stack silently without me opting in starts to install extensions into other things like jupyterlab.

**Comment by travigd** [comment]
This is fair but also has some cons.

It requires extra steps for people who want to use Interact (for example) in Jupyter or JupyterLab to go through an extra step. Things like IJulia also do this (writing to your local jupyter config directory) so it's not unheard of (though IJulia is also much more closely integrated with Jupyter than we are).

It might be good to surface a message when you run `using WebIO` when IJulia is loaded and it detects that it isn't installed (or just surfacing a message via HTML in the notebook) with instructions.

**Comment by travigd** [comment]
I'm addressing this in #319.

I think the best course of action is going to be to not install by default (since we're a common dependency) and surface information about how to easily install the extension when we detect that we're running in Jupyter.

**Comment by travigd** [comment]
Closed by #319.
