### ISSUE TITLE
Interact on IJulia only works after kernel restart

### ISSUE THREAD

**Issue by hhaensel** [JuliaGizmos/WebIO.jl#316]
For kernels >= 0.7 Interact on IJulia does not work if the kernel is loaded for the first time.
A minimal example is
```
using Interact
s = slider(1:10)
x = observe(s)
display.([s, x]);
```

![image](https://user-images.githubusercontent.com/31985040/60420180-607bfd80-9be7-11e9-86e9-dac06ab1132a.png)

The slider is drawn and can be moved, but the attached observable is not responsive.

After a kernel restart, though, everything works as expected.

![image](https://user-images.githubusercontent.com/31985040/60420417-fc0d6e00-9be7-11e9-998d-54cd1b5d7491.png)

**Comment by travigd** [comment]
I can't reproduce this on the latest WebIO.

Please try updating WebIO, running `WebIO.install_jupyter_nbextension()`, and let us know if you have this issue still -- or if it's resolved, I always like hearing good news! :^)

**Comment by hhaensel** [comment]
Sorry for late answering (holidays ... :-) )
On my Windows 7 installation the issue is still existing, even with the current master.
I will check on my Windows 10 later this week

**Comment by hhaensel** [comment]
I did check now on Windows 10 with Julia 1.1.1 and Firefox it works like a charm.
So probably not a WebIO issue ...
