### ISSUE TITLE
Creating tags but not releases

### ISSUE THREAD

**Issue by tkoolen** [JuliaGizmos/WebIO.jl#326]
For the 0.8.7 and 0.8.8 releases, I see that tags have been created, but there's no release description like there is for e.g. 0.8.6.

**Comment by travigd** [comment]
We use Lerna to create tags (because it insists on doing itself). If tagbot could create releases only that might be good. Maybe we can also tell Lerna to do it?

**Comment by travigd** [comment]
Modified the title to reflect the issue. :^)
