### ISSUE TITLE
WebIO labextension installation error: No linked package for @webio/webio

### ISSUE THREAD

**Issue by Masacroso** [JuliaGizmos/WebIO.jl#334]
As the title says, the bug is that when installing the webio labextension I get the error `No linked package for @webio/webio`. The complete behavior is described below.

---

I installed the extension this way:
- first calling `julia.exe` from an anaconda prompt (in windows 10)

- after what I did was `using WebIO` and after `WebIO.install_jupyter_labextension()` to install the labextension.

Then this error appeared in the process of installation
```
julia> WebIO.install_jupyter_labextension()
[ Info: Using default Jupyter executable at `'C:\Users\p5b\Anaconda3\Scripts\jupyter.exe'`; to use a different executable, see the documentation by running `?WebIO.install_jupyter_labextension`.
An error occured.
ValueError: No linked package for @webio/webio
See the log file for details:  D:\temp\jupyterlab-debug-ifmmargl.log
Uninstalling @webio/jupyter-lab-provider from C:\Users\p5b\Anaconda3\share\jupyter\lab\extensions
[LabBuildApp] JupyterLab 1.0.2
[LabBuildApp] Building in C:\Users\p5b\Anaconda3\share\jupyter\lab
[LabBuildApp] Building jupyterlab assets
Process(`'C:\Users\p5b\Anaconda3\Scripts\jupyter.exe' lab build`, ProcessExited(0))
```

and the log file says:

```
Traceback (most recent call last):

  File "C:\Users\p5b\Anaconda3\lib\site-packages\jupyterlab\debuglog.py", line 47, in debug_logging
    yield

  File "C:\Users\p5b\Anaconda3\lib\site-packages\jupyterlab\labextensions.py", line 82, in start
    ans = self.run_task()

  File "C:\Users\p5b\Anaconda3\lib\site-packages\jupyterlab\labextensions.py", line 152, in run_task
    for arg in self.extra_args

  File "C:\Users\p5b\Anaconda3\lib\site-packages\jupyterlab\labextensions.py", line 152, in <listcomp>
    for arg in self.extra_args

  File "C:\Users\p5b\Anaconda3\lib\site-packages\jupyterlab\commands.py", line 441, in unlink_package
    return handler.unlink_package(package)

  File "C:\Users\p5b\Anaconda3\lib\site-packages\jupyterlab\commands.py", line 849, in unlink_package
    raise ValueError('No linked package for %s' % path)

ValueError: No linked package for @webio/webio

Exiting application: jupyter
```

Also: calling for `jupyter labextension list` it says that the extension is ok, that is
```
C:\Users\p5b\AppData\Local\Julia-1.1.1\bin>jupyter labextension list
JupyterLab v1.0.2
Known labextensions:
   app dir: C:\Users\p5b\Anaconda3\share\jupyter\lab
        @webio/jupyter-lab-provider v0.8.9 enabled  ok
```
However  testing a plot in jupyterlab with PlotlyJS it just show an empty cell. There is no error (not "webio not detected" this time), just an empty cell as the output (but the same code works in the classical jupyter notebook).

To provide more context Im using these packages in Julia:
```
[c52e3926] Atom v0.8.8
  [6e4b80f9] BenchmarkTools v0.4.2
  [ad839575] Blink v0.12.0
  [336ed68f] CSV v0.5.9
  [5ae59095] Colors v0.9.5
  [a93c6f00] DataFrames v0.19.1
  [6e83dbb3] Discretizers v3.0.1
  [31c24e10] Distributions v0.21.1
  [28b8d3ca] GR v0.41.0
  [f67ccb44] HDF5 v0.12.0
  [7073ff75] IJulia v1.19.0
  [c601a237] Interact v0.10.2
  [a98d9a8b] Interpolations v0.12.2
  [033835bb] JLD2 v0.1.2
  [e5e0dc1b] Juno v0.7.0
  [5ab0869b] KernelDensity v0.5.1
  [b964fa9f] LaTeXStrings v1.0.3
  [ee78f7c6] Makie v0.9.4
  [47be7bcc] ORCA v0.2.1
  [3b7a836e] PGFPlots v3.1.3
  [8314cec4] PGFPlotsX v1.1.0
  [f0f68f2c] PlotlyJS v0.12.5
  [91a5bcdd] Plots v0.26.0
  [d330b81b] PyPlot v2.8.1
  [6f49c342] RCall v0.13.3
  [ce6b1742] RDatasets v0.6.3
  [e6cf234a] RandomNumbers v1.3.0
  [2913bbd2] StatsBase v0.32.0
  [0f1e0344] WebIO v0.8.9
```

**Comment by travigd** [comment]
Ah - this is not an error (my apologies for suggesting otherwise on Slack).

What happens is that part of the installation process will try to run `jupyter labextension unlink @webio/webio` but if **that** fails then it's fine (it exists to clean-up previous installations but if there is no previous installation, it just does nothing).

If WebIO isn't working, please open a new issue with more details about what's not working (e.g. package version, operating system, what you see in the notebook, etc.). Thanks!

**Comment by Masacroso** [comment]
> 
> 
> Ah - this is not an error (my apologies for suggesting otherwise on Slack).
> 
> What happens is that part of the installation process will try to run `jupyter labextension unlink @webio/webio` but if **that** fails then it's fine (it exists to clean-up previous installations but if there is no previous installation, it just does nothing).
> 
> If WebIO isn't working, please open a new issue with more details about what's not working (e.g. package version, operating system, what you see in the notebook, etc.). Thanks!

I already did that: the WebIO version, operating system, what is now working and how it shows in Jupyter notebook and all the complete behavior is contained in the message that starts this thread.

**Comment by flutefreak7** [comment]
It would be a great quality of life improvement if this were fixed. I assumed something had gone wrong when I got this error.
