### ISSUE TITLE
WebIO can't be built on AppVeyor

### ISSUE THREAD

**Issue by giordano** [JuliaGizmos/WebIO.jl#335]
I have a package indirectly depending on WebIO (it depends on Interact, I think this uses WebIO), but it fails to build AppVeyor, e.g. see https://ci.appveyor.com/project/giordano/astroimages-jl/build/job/kl8vm0riq77low2h.  I restarted this job several times, build always fails.

I don't know if it's a general problem on Windows or it's specific to AppVeyor (I see that this repository doesn't run tests on AppVeyor, is it related?).  I also don't know if the testing failure is somewhat related to WebIO or not (I would guess it isn't, but removing the incomplete build of a dependent package would help to chase the problem).

**Comment by travigd** [comment]
Closed by #336 - will release soon.
