### ISSUE TITLE
Incorrect function name in docstring for install_jupyter_nbextension

### ISSUE THREAD

**Issue by rdeits** [JuliaGizmos/WebIO.jl#349]
The docstring for `install_jupyter_nbextension` refers to the function as `install_webio_nbextension`: https://github.com/JuliaGizmos/WebIO.jl/blob/973fdd1e868ad594ec458ba3b2baed389180999e/deps/jupyter.jl#L165-L172

I would just make a PR, but I can't check out the code locally right now. 

By the way, we could consider using DocStringExtensions to automate this sort of thing.

**Comment by polloparatodos** [comment]
I made a PR for this, though I hope I am not stepping on any toes. :)

**Comment by travigd** [comment]
Closed by #374.
