### ISSUE TITLE
Document the messaging protocol

### ISSUE THREAD

**Issue by kskyten** [JuliaGizmos/WebIO.jl#359]
WebIO seems to be geared towards sending whole DOM objects from Julia. I'm interested in creating a front end in javascript and just communicating data bi-directionally via websockets. How would I do this? Could you explain how the messaging protocol works?

**Comment by travigd** [comment]
I don't think WebIO would be a good choice for a project like you're describing that doesn't utilize the DOM functionality that WebIO is tightly integrated with.

A better approach might be to roll your own messaging protocol using WebSockets.jl and sending JSON-serialized messages.
