### ISSUE TITLE
dom"" macro problem

### ISSUE THREAD

**Issue by dimitraVrs** [JuliaGizmos/WebIO.jl#363]
Hi!
I am trying to write the following html in julia ,using the dom"".
```
</head>

<body>
  
  <div id="myDiv"><!-- Plotly chart will be drawn inside this DIV --></div>
  <script>
    <!-- JAVASCRIPT CODE GOES HERE -->
	var data = [{
  		x: ['giraffes', 'orangutans', 'monkeys'],
  		y: [20, 14, 23],
  		type: 'bar'
        }];

	Plotly.newPlot('myDiv', data, {}, {showSendToCloud:true});
  </script>
</body>
```

So, I have written :
```
dom"h1"(The books in genres plot is:)

dom"head"(
            			dom"script[src=https://cdn.plot.ly/plotly-latest.min.js]"

)
dom"body"(
            			dom"div#myDiv"
            			dom"script[type=text/javascript,src=/home/dimitra/testPlot.js]"(
					var data = [{
  						x: ['giraffes', 'orangutans', 'monkeys'],
  						y: [20, 14, 23],
  						type: 'bar'
        				}];

					Plotly.newPlot('myDiv', data, {}, {showSendToCloud:true});
				)

)
```
But, I got a syntax error because of ) or  comma missing. I cannot find where it should be placed. Can you help?

Also, I have the following question: In the secong sript for Javascript code, the Javascript code should be inside js"" macro or is it right to write it the way I have wrotten the code?

Thank you!

**Comment by polloparatodos** [comment]
Did you get this resolved? The following should resolve the `syntax: missing comma or ) in argument list` LoadError:

```
dom"h1"("The books in genres plot is:")

dom"head"(
  dom"script"(
    dom"src", ["https://cdn.plot.ly/plotly-latest.min.js"]
  )
)
```

Or to maintain code consistency and not use arg lists:

using WebIO

```
dom"h1"("The books in genres plot is:")

dom"head"(
  dom"script"(
    dom"src"(
      ["https://cdn.plot.ly/plotly-latest.min.js"]
    )
  )
)
```

I didn't fully go through the second part to see what could help, though at a glance it looks to be similar enough and might just need quoting. I looked over the [example references](https://github.com/JuliaGizmos/WebIO.jl/blob/master/examples/jupyter-demo.ipynb) which may help with pulling in JS dependencies. `@js` might be better, though I am still pretty new to using this package so I can't say for sure.

**Comment by travigd** [comment]
The `dom` macro is mostly for relatively simple things (at least the part that goes inside the string).

```julia
dom"div"(
    # Children of the div here
)
```

We support some limited convenience syntax.
```julia
julia> dom"div#my-id"()
(div { id="my-id" })

julia> dom"div.my-class"()
(div { className="my-class" })

julia> dom"div[data-foo=foo]"()
(div { attributes=Dict("data-foo" => "foo") })
```

For anything more complicated, it makes more sense to stop putting things in the string.

```julia
julia> dom"script"(
           src="https://cdn.plot.ly/plotly-latest.min.js",
       )
(script { src="https://cdn.plot.ly/plotly-latest.min.js" })

# Node syntax where the first argument is the type of DOM node.
julia> node(:script, src="https://cdn.plot.ly/plotly-latest.min.js")
(script { src="https://cdn.plot.ly/plotly-latest.min.js" })
```

---

One of the issues with your example is that it's not valid Julia syntax and it doesn't really accurately reflect how WebIO abstracts DOM nodes.

```julia
# Good, <head /> is a valid DOM node.
dom"head"(
  # Good, <script /> is a valid DOM node.
  dom"script"(
    # Not quite. src is an attribute on the <script /> node, not a nested DOM node.
    dom"src"(
      ["https://cdn.plot.ly/plotly-latest.min.js"]
    )
  )
)
```

The problematic example above would give the following HTML.
```html
<head>
  <script>
    <src>
      https://cdn.plot.ly/plotly-latest.min.js
    </src>
  </script>
</head>
```

whereas you want this instead:
```html
<head>
  <script src="https://cdn.plot.ly/plotly-latest.min.js" />
</head>
```

**Comment by travigd** [comment]
In the initial code snippet, we want to generate this HTML.

```julia
</head>

<body>
  
  <div id="myDiv"><!-- Plotly chart will be drawn inside this DIV --></div>
  <script>
    <!-- JAVASCRIPT CODE GOES HERE -->
	var data = [{
  		x: ['giraffes', 'orangutans', 'monkeys'],
  		y: [20, 14, 23],
  		type: 'bar'
        }];

	Plotly.newPlot('myDiv', data, {}, {showSendToCloud:true});
  </script>
</body>
```

We can do this as follows (using the `node(...)` syntax rather than the `dom"..."(...)` syntax).
```julia
node(:body,
    node(:div, id="myDiv"),
    node(:script,
        """
        var data = ...;
        Plotly.newPlot('myDiv', data, {}, {showSendToCloud: true});
        """
    ),
)
```

**Comment by polloparatodos** [comment]
Thanks! I was a bit stumped myself, but I see where I went wrong and the examples you posted help a lot
