### ISSUE TITLE
Compat between released version of WebIO (0.8.13) and JSExpr not properly registered? 

### ISSUE THREAD

**Issue by tkoolen** [JuliaGizmos/WebIO.jl#373]
In an empty project on Julia 1.3, I `add WebIO` and then `add JSExpr`. `status -m` shows that the resolver has given me WebIO v0.8.13 and JSExpr v1.0.1. However, WebIO.jl's `Project.toml` for version 0.8.13 contains

https://github.com/JuliaGizmos/WebIO.jl/blob/e160f9551b36b85da89bc0d18f30fdc4bf7b2468/Project.toml#L38

which I understand should be interpreted as `[0.5.0, 0.6.0)`. Could it be that the `0.5` bound somehow didn't make it into the [PR to JuliaRegistries/General](https://github.com/JuliaRegistries/General/pull/7046)? I see that it was merged manually, so it appears to me that there's room for error there.

**Comment by travigd** [comment]
Thank you for flagging. The actual issue is a bit more complex that I realized.

> JSExpr v0.5 depends on WebIO, but in v1.0, we dropped the dependency (and were planning on reversing it for WebIO v1.0). I forgot that WebIO doesn't actually depend on JSExpr though when I added the compat entry.

I'm not sure what the solution to this is. For now, pinning JSExpr to v0.5 works. Sorry for the issues!

**Comment by travigd** [comment]
Should be "fixed" by https://github.com/JuliaRegistries/General/pull/7165/.
