### ISSUE TITLE
WebIO + Interact + Mux does not work on pages other than "/"

### ISSUE THREAD

**Issue by cstjean** [JuliaGizmos/WebIO.jl#382]
On the current #master, with `Interact v0.10.3` and `Mux v0.7.1`, Interact widgets with Mux only work on `/`:

```julia
julia> using WebIO, Interact, Mux
   
julia> function gui()
           but = button("click me")
           on(but) do _
               println("was clicked")
           end
           but
       end
gui (generic function with 1 method)

julia> Mux.@app app = (Mux.defaults,
                       page("/", req->gui()),
                       page("/hallo", req->gui()),
                       Mux.notfound())

julia> webio_serve(app, 8000)
Task (runnable) @0x00007f359a5adae0
```

Then the button at http://localhost:8000 works, but not the one at http://localhost:8000/hallo

I believe that @stefan911 found the solution in https://github.com/JuliaGizmos/WebIO.jl/issues/241#issuecomment-452099875 but I can't quite figure it out from his comment.

**Comment by etpinard** [comment]
Judging by 

https://github.com/JuliaGizmos/WebIO.jl/blob/ee52ba2345169315452a59c8d8e4c4d35c2dc325/src/providers/mux.jl#L20-L29

the problem might be in 

https://github.com/JuliaGizmos/WebIO.jl/blob/ee52ba2345169315452a59c8d8e4c4d35c2dc325/packages/mux-provider/src/mux.ts#L9-L16

which for http://localhost:8000/hallo returns `ws://localhost:8000/hallo/webio-socket`, but we need `ws://localhost:8000/webio-socket/hallo` for `Mux.route("/webio-socket", create_socket)` to pick up the request.

---

Before I make a PR, any info on the _best_ way to test patches in the JS code would be much appreciated. Thanks!
