### ISSUE TITLE
Dependency trees

### ISSUE THREAD

**Issue by shashi** [JuliaGizmos/WebIO.jl#40]
Only flat dependencies can be specified at the moment, and all dependencies are loaded asynchronously.

Most use cases however require some dependencies to loaded after others. e.g. jquery-ui must be loaded after jquery.

The suggested implementation from the SystemJS gitter is to create a tree of dependencies using promises. The julia API could be something like `Async(Sync("jquery.js", "jquery-ui.js"), "moment.js")`, ondependencies will get the flattened modules i.e. jQuery, jQueryUI and Moment.

**Comment by JobJob** [comment]
I like this syntax 👍

**Comment by shashi** [comment]
in #44
