### ISSUE TITLE
WebIO not detected (Julia)

### ISSUE THREAD

**Issue by XxAakashxX** [JuliaGizmos/WebIO.jl#423]
I was trying to use **Plotly package** in Julia(Jupyter Notebook). As I tried the following command:
`Plotly.plot(stats["PetalWidth"], stats["Class"])`
It returns :
```
WebIO not detected.

Please read the troubleshooting guide for more information on how to resolve this issue.

https://juliagizmos.github.io/WebIO.jl/latest/troubleshooting/not-detected/****
```
After applying the steps mentioned on the link like running the following commands:
```
Pkg.add("WebIO")
using WebIO
WebIO.install_jupyter_nbextension()
```
And then running these in terminal:
```
jupyter nbextension uninstall --user webio/main
jupyter nbextension uninstall --user webio-jupyter-notebook
```
But still the problem remains **unresolved**! It still keeps saying "**WebIO not detected**"
What should i do?

Even My WebIO is also shown connected when I see the notebook extension dashboard!
![Annotation 2020-03-27 070116](https://user-images.githubusercontent.com/60868717/87214602-c008ff00-c34b-11ea-85d3-76b9e42fcbeb.png)

**Comment by shashi** [comment]
Did you restart the notebook server?

**Comment by Jdbeck66** [comment]
Happening to me as well. Exact same. I did also restart the notebook kernel. I'm running Julia 1.5.3 and WebIO v0.8.15, Interact v0.10.3, Conda v1.5.0 and IJulia v1.23.0

**Comment by travigd** [comment]
Did you restart the notebook server (e.g., the `jupyter notebook` command or `IJulia.notebook()`) -- not just the kernel?

**Comment by Jdbeck66** [comment]
Yes, that was the problem.
