### ISSUE TITLE
WebIO not detected

### ISSUE THREAD

**Issue by luli2949** [JuliaGizmos/WebIO.jl#446]
Hi there, 

I was trying to run Julia on Google Colab but was getting the error WebIO not detected. 

I've tried the troubleshooting instructions in WebIO and also tried restarting the notebook several times. However, I still get the same error. I'm using Julia 1.5 and MacOS.

Here is the link to the Colab notebook: https://colab.research.google.com/drive/1-PoTD44o6gLonnC3Uf93aHVgPBQ7Vngu?usp=sharing

Below are my installations:

`Pkg.add(["WebIO", "InteractBase", "ORCA", "PlotlyJS", "Interact", "IJulia", "Eirene", "DelimitedFiles"]);
using WebIO;
WebIO.install_jupyter_nbextension();
using PlotlyJS, IJulia, WebIO, Interact, WebIO, Eirene, DelimitedFiles;
pc = readdlm(download("https://raw.githubusercontent.com/luli2949/TDA_Analysis/master/points1.csv"), ',');
D = eirene(pc, model="pc")
plotbarcode_pjs(D, dim=1)
`

Thank you so much for your help!

**Comment by travigd** [comment]
It's probably not possible to run WebIO on colab unfortunately. The frontend (in this case colab) has to support it.

**Comment by luli2949** [comment]
Got it. Thanks!
