### ISSUE TITLE
Support basic usage within Pluto

### ISSUE THREAD

**Issue by schneiderfelipe** [JuliaGizmos/WebIO.jl#452]
Is there a way to allow minimal support in [Pluto.jl](https://github.com/fonsp/Pluto.jl)?

![WebIO not detected in Pluto](https://user-images.githubusercontent.com/37125/113865646-b39ebf00-9782-11eb-8c84-f6b68344863b.png)

```julia
julia> versioninfo()
Julia Version 1.4.1
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: AMD Ryzen 5 1600 Six-Core Processor
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-8.0.1 (ORCJIT, znver1)
Environment:
  JULIA_NUM_THREADS = 12

(@v1.4) pkg> st WebIO Pluto
Status `~/.julia/environments/v1.4/Project.toml`
  [c3e4b0f8] Pluto v0.14.0
  [0f1e0344] WebIO v0.8.15
```

**Comment by travigd** [comment]
@fonsp Thoughts?

To some extent, I'm not sure how well it would work with respect to Pluto's reactivity.

**Comment by fonsp** [comment]
we are almost done! https://github.com/fonsp/Pluto.jl/pull/991

**Comment by travigd** [comment]
Awesome!

**Comment by schneiderfelipe** [comment]
> we are almost done! [fonsp/Pluto.jl#991](https://github.com/fonsp/Pluto.jl/pull/991)

@fonsp I wasn't aware of that PR! This is amazing!
