### ISSUE TITLE
Observables 0.4

### ISSUE THREAD

**Issue by Datseris** [JuliaGizmos/WebIO.jl#455]
Hi, can you please tag a patch release that bumps observables compatibility to 0.4? There wasn't any major breaking change. However, with your current Project.toml it is not possible to use Atom and Makie in the same environment...

**Comment by hhaensel** [comment]
Just realised that there is already a PR #456

**Comment by hhaensel** [comment]
I think this can be closed as the above PR is merged.

**Comment by Datseris** [comment]
Did you tag a new version? Please close it when a new version is tagged.

**Comment by jonas-kr** [comment]
Since in Observables 0.4 the function `Observables.setexcludinghandlersinterface` has been replaced by `Observables.setexcludinghandlers!`, the function `set_nosync` in scope.jl has to be adjusted as follows:
```
function set_nosync(ob, val)
    Observables.setexcludinghandlers!(ob, val)
end
```
In doing so, however, the compatibility with older releases of Observables is lost.

**Comment by hhaensel** [comment]
Why not checking for the existence of `setexcludinghandlers!`, e.g.

```julia
function set_nosync(ob, val)
    if isdefined(Observables, :setexcludinghandlers!)
        Observables.setexcludinghandlers!(ob, val)
    else
        Observables.setexcludinghandlers(ob, val, x -> !(x isa SyncCallback))
    end
end
```

**Comment by Datseris** [comment]
> In doing so, however, the compatibility with older releases of Observables is lost.

Just tag 0.9 to signal a breaking release, given that neither of these packages is in 1.0 and when observables went from 0.3 to 0.4 it signalled a breaking release as well.

**Comment by pdeffebach** [comment]
Bumping this, I am running into a compatibility issue [here](https://github.com/pdeffebach/FloatingTableView.jl/issues/25), would be great to get a new release, even with a clunky `if...else` block.

**Comment by hhaensel** [comment]
It's good practice to include such a compatibility version as minor change and then publish a breaking release without it.

**Comment by galran** [comment]
bump. this is causing compatibility issues with the new WGLMakie - any chance of an update soon?
