### ISSUE TITLE
WebIO Not Detected - Jupyterlab Extensions - Nodejs 12

### ISSUE THREAD

**Issue by jim2236** [JuliaGizmos/WebIO.jl#459]
I want to run the Interact package and use @manipulate.  The problem appears to be issues with installing Jupyterlab extensions, no linked package for @webio/webio, and finding nodejs 12.  

Relevant facts
- MacOS 11.4
- New installations of Anaconda (Conda version 4.10.2) and Julia 1.6.1

(base) perry@greenmosss-MacBook-Pro ~ % conda --version
conda 4.10.2

julia> versioninfo()
Julia Version 1.6.1
Commit 6aaedecc44 (2021-04-23 05:59 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.7.0)
  CPU: Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, skylake)

- Installed nodejs version 12.4.0, 

# Name                    Version                   Build  Channel
nodejs                    12.4.0               h6de7cb9_0    conda-forge/label/cf202003

- Jupyter lab extensions

JupyterLab v3.0.14
/Users/perry/opt/anaconda3/share/jupyter/labextensions
        @jupyter-widgets/jupyterlab-manager v3.0.0 enabled OK (python, jupyterlab_widgets)

From the REPL, I’m using IJulia, running juypterlab(), and working in a notebook.  In a notebook cell, I’m using WebIO, Interact.  

using WebIO, Interact

In the next cell, I ran code with the @manipulate

x = range(0; stop=2pi, length=100)
@manipulate for fcn in (sin, cos)
    y = fcn.(x)
    scatter(x, y; label="$fcn", xlabel="x", ylabel="$(fcn)(x)")
end

…and receive an error stating “WebIO not detected”

WebIO not detected.
Please read the troubleshooting guide for more information on how to resolve this issue.
https://juliagizmos.github.io/WebIO.jl/latest/troubleshooting/not-detected/

I ran #WebIO.install_jupyter_labextension(condajl=true) in the notebook

using WebIO, Interact
WebIO.install_jupyter_labextension(condajl=true)

…which returned the following errors

┌ Info: Using default Jupyter executable at setenv(`/Users/perry/.julia/conda/3/bin/jupyter`,["XPC_FLAGS=0x0", "_CE_M=", "PATH=/Users/perry/.julia/conda/3/bin:/Applications/Julia-1.6.app/Contents/Resources/julia/bin:/Users/perry/.julia/conda/3/bin:/Users/perry/opt/anaconda3/bin:/Users/perry/opt/anaconda3/condabin:/Library/Frameworks/Python.framework/Versions/3.9/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/Library/TeX/texbin:/Applications/Postgres.app/Contents/Versions/latest/bin", "PWD=/Users/perry", "GRDIR=/Users/perry/.julia/artifacts/faca4a17b11e6d61d561c27e5658627c77bebe5d/lib/..", "XPC_SERVICE_NAME=0", "TERM_PROGRAM=Apple_Terminal", "COLUMNS=80", "SHELL=/bin/zsh", "GKS_ENCODING=utf8", "__CF_USER_TEXT_ENCODING=0x1F7:0x0:0x0", "OPENBLAS_NUM_THREADS=8", "JPY_PARENT_PID=14310", "__CFBundleIdentifier=com.apple.Terminal", "GKS_FONTPATH=/Users/perry/.julia/artifacts/faca4a17b11e6d61d561c27e5658627c77bebe5d/lib/..", "TMPDIR=/var/folders/4j/xddqf5y15zz5dxd4__qx50900000gq/T/", "CONDARC=/Users/perry/.julia/conda/3/condarc-julia.yml", "GKS_USE_CAIRO_PNG=true", "FONTCONFIG_PATH=/Users/perry/.julia/artifacts/59dd5a9a46bbbc4aa432a1e0a1c20b847be04460/etc/fonts", "LANG=en_US.UTF-8", "LOGNAME=perry", "SHLVL=1", "CONDA_PREFIX=/Users/perry/.julia/conda/3", "SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.gjUH928RaV/Listeners", "TERM_SESSION_ID=6A2F0102-E0D3-4B00-A12B-8DE0E29BE6EA", "OLDPWD=/Users/perry", "FONTCONFIG_FILE=/Users/perry/.julia/artifacts/59dd5a9a46bbbc4aa432a1e0a1c20b847be04460/etc/fonts/fonts.conf", "_=/usr/local/bin/julia", "_CE_CONDA=", "USER=perry", "LINES=30", "MPLBACKEND=Agg", "GKS_FILEPATH=/var/folders/4j/xddqf5y15zz5dxd4__qx50900000gq/T/jl_UmgMVM.png", "TERM=xterm-256color", "HOME=/Users/perry", "TERM_PROGRAM_VERSION=440", "OPENBLAS_MAIN_FREE=1", "PYTHONIOENCODING=UTF-8", "GKSwstype=svg"]); to use a different executable, see the documentation by running `?WebIO.install_jupyter_labextension`.
└ @ WebIO /Users/perry/.julia/packages/WebIO/Fy9h1/deps/jupyter.jl:198

An error occured.
ValueError: No linked package for @webio/webio
See the log file for details:  /var/folders/4j/xddqf5y15zz5dxd4__qx50900000gq/T/jupyterlab-debug-8hnfmj91.log
An error occured.
ValueError: Please install nodejs >=12.0.0 before continuing. nodejs may be installed using conda or directly from the nodejs website.
See the log file for details:  /var/folders/4j/xddqf5y15zz5dxd4__qx50900000gq/T/jupyterlab-debug-m6wq_50i.log
An error occured.
ValueError: Please install nodejs >=12.0.0 before continuing. nodejs may be installed using conda or directly from the nodejs website.
See the log file for details:  /var/folders/4j/xddqf5y15zz5dxd4__qx50900000gq/T/jupyterlab-debug-gk0xrqeh.log

failed process: Process(setenv(`/Users/perry/.julia/conda/3/bin/jupyter labextension install --no-build @webio/jupyter-lab-provider@0.8.15`,["XPC_FLAGS=0x0", "_CE_M=", "PATH=/Users/perry/.julia/conda/3/bin:/Applications/Julia-1.6.app/Contents/Resources/julia/bin:/Users/perry/.julia/conda/3/bin:/Users/perry/opt/anaconda3/bin:/Users/perry/opt/anaconda3/condabin:/Library/Frameworks/Python.framework/Versions/3.9/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/Library/TeX/texbin:/Applications/Postgres.app/Contents/Versions/latest/bin", "PWD=/Users/perry", "GRDIR=/Users/perry/.julia/artifacts/faca4a17b11e6d61d561c27e5658627c77bebe5d/lib/..", "XPC_SERVICE_NAME=0", "TERM_PROGRAM=Apple_Terminal", "COLUMNS=80", "SHELL=/bin/zsh", "GKS_ENCODING=utf8"  …  "USER=perry", "LINES=30", "MPLBACKEND=Agg", "GKS_FILEPATH=/var/folders/4j/xddqf5y15zz5dxd4__qx50900000gq/T/jl_UmgMVM.png", "TERM=xterm-256color", "HOME=/Users/perry", "TERM_PROGRAM_VERSION=440", "OPENBLAS_MAIN_FREE=1", "PYTHONIOENCODING=UTF-8", "GKSwstype=svg"]), ProcessExited(1)) [1]

Stacktrace:
 [1] pipeline_error
   @ ./process.jl:525 [inlined]
 [2] run(::Cmd; wait::Bool)
   @ Base ./process.jl:440
 [3] run
   @ ./process.jl:438 [inlined]
 [4] install_jupyter_labextension(jupyter::Nothing; force_conda_jupyter::Nothing, condajl::Bool, dev::Bool)
   @ WebIO ~/.julia/packages/WebIO/Fy9h1/deps/jupyter.jl:216
 [5] top-level scope
   @ In[17]:2
 [6] eval
   @ ./boot.jl:360 [inlined]
 [7] include_string(mapexpr::typeof(REPL.softscope), mod::Module, code::String, filename::String)
   @ Base ./loading.jl:1094

Catting the first referenced log files displays the following information:

(base) perry@greenmosss-MacBook-Pro ~ % cat /var/folders/4j/xddqf5y15zz5dxd4__qx50900000gq/T/jupyterlab-debug-lh_7wrms.log
Yarn configuration loaded.
Traceback (most recent call last):

  File "/Users/perry/.julia/conda/3/lib/python3.7/site-packages/jupyterlab/debuglog.py", line 47, in debug_logging
    yield

  File "/Users/perry/.julia/conda/3/lib/python3.7/site-packages/jupyterlab/labextensions.py", line 128, in start
    ans = self.run_task()

  File "/Users/perry/.julia/conda/3/lib/python3.7/site-packages/jupyterlab/labextensions.py", line 314, in run_task
    for arg in self.extra_args

  File "/Users/perry/.julia/conda/3/lib/python3.7/site-packages/jupyterlab/labextensions.py", line 314, in <listcomp>
    for arg in self.extra_args

  File "/Users/perry/.julia/conda/3/lib/python3.7/site-packages/jupyterlab/commands.py", line 539, in unlink_package
    return handler.unlink_package(package)

  File "/Users/perry/.julia/conda/3/lib/python3.7/site-packages/jupyterlab/commands.py", line 1002, in unlink_package
    raise ValueError('No linked package for %s' % path)

ValueError: No linked package for @webio/webio

Exiting application: lab

Catting the second reference log file displays the following

(base) perry@greenmosss-MacBook-Pro ~ % cat /var/folders/4j/xddqf5y15zz5dxd4__qx50900000gq/T/jupyterlab-debug-ob844jp9.log
Traceback (most recent call last):

  File "/Users/perry/.julia/conda/3/lib/python3.7/site-packages/jupyterlab/commands.py", line 1890, in _node_check
    output = subprocess.check_output([node, 'node-version-check.js'], cwd=HERE)

  File "/Users/perry/.julia/conda/3/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout

  File "/Users/perry/.julia/conda/3/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)

subprocess.CalledProcessError: Command '['/Users/perry/.julia/conda/3/bin/node', 'node-version-check.js']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/Users/perry/.julia/conda/3/lib/python3.7/site-packages/jupyterlab/debuglog.py", line 47, in debug_logging
    yield

  File "/Users/perry/.julia/conda/3/lib/python3.7/site-packages/jupyterlab/labextensions.py", line 128, in start
    ans = self.run_task()

  File "/Users/perry/.julia/conda/3/lib/python3.7/site-packages/jupyterlab/labextensions.py", line 336, in run_task
    for arg in self.extra_args

  File "/Users/perry/.julia/conda/3/lib/python3.7/site-packages/jupyterlab/labextensions.py", line 336, in <listcomp>
    for arg in self.extra_args

  File "/Users/perry/.julia/conda/3/lib/python3.7/site-packages/jupyterlab/commands.py", line 407, in uninstall_extension
    _node_check(app_options.logger)

  File "/Users/perry/.julia/conda/3/lib/python3.7/site-packages/jupyterlab/commands.py", line 1896, in _node_check
    raise ValueError(msg)

ValueError: Please install nodejs >=12.0.0 before continuing. nodejs may be installed using conda or directly from the nodejs website.

Exiting application: lab

Catting the third referenced log file displays the following:

(base) perry@greenmosss-MacBook-Pro ~ % cat /var/folders/4j/xddqf5y15zz5dxd4__qx50900000gq/T/jupyterlab-debug-xut35bk0.log
Traceback (most recent call last):

  File "/Users/perry/.julia/conda/3/lib/python3.7/site-packages/jupyterlab/commands.py", line 1890, in _node_check
    output = subprocess.check_output([node, 'node-version-check.js'], cwd=HERE)

  File "/Users/perry/.julia/conda/3/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout

  File "/Users/perry/.julia/conda/3/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)

subprocess.CalledProcessError: Command '['/Users/perry/.julia/conda/3/bin/node', 'node-version-check.js']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/Users/perry/.julia/conda/3/lib/python3.7/site-packages/jupyterlab/debuglog.py", line 47, in debug_logging
    yield

  File "/Users/perry/.julia/conda/3/lib/python3.7/site-packages/jupyterlab/labextensions.py", line 128, in start
    ans = self.run_task()

  File "/Users/perry/.julia/conda/3/lib/python3.7/site-packages/jupyterlab/labextensions.py", line 179, in run_task
    for i, arg in enumerate(self.extra_args)

  File "/Users/perry/.julia/conda/3/lib/python3.7/site-packages/jupyterlab/labextensions.py", line 179, in <listcomp>
    for i, arg in enumerate(self.extra_args)

  File "/Users/perry/.julia/conda/3/lib/python3.7/site-packages/jupyterlab/commands.py", line 396, in install_extension
    _node_check(app_options.logger)

  File "/Users/perry/.julia/conda/3/lib/python3.7/site-packages/jupyterlab/commands.py", line 1896, in _node_check
    raise ValueError(msg)

ValueError: Please install nodejs >=12.0.0 before continuing. nodejs may be installed using conda or directly from the nodejs website.

Exiting application: lab

From what I see, part or all of the issue may be that Jupiter cannot see the nodejs 12 installation, but am unsure how to correct that problem.  I’ve researched the issues and see some conversation but have not found a viable solution.  

I’d appreciate any insight and help that can be provided.

**Comment by travigd** [comment]
You need to install nodejs to use Jupyterlab extensions. I think something like `conda install nodejs` should work.

**Comment by jim2236** [comment]
I did install nodejs using conda.  nodejs version 12.4.0 is installed, noted above.

**Comment by travigd** [comment]
You might need to update the version of Node in Julia's Conda installation:
```
/Users/perry/.julia/conda/3/bin/conda install 'nodejs>=12'
```

**Comment by jim2236** [comment]
I updated the version of Node in Julia's installation, as recommended above.  
--------------------------------------
(base) perry@greenmosss-MacBook-Pro bin % /Users/perry/.julia/conda/3/bin/conda install ‘nodejs>=12'
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /Users/perry/opt/anaconda3

  added / updated specs:
    - nodejs[version='>=12']


The following packages will be UPDATED:

  ca-certificates    conda-forge/label/cf202003::ca-certif~ --> pkgs/main::ca-certificates-2021.5.25-hecd8cb5_1

The following packages will be SUPERSEDED by a higher-priority channel:

  openssl            conda-forge::openssl-1.1.1k-h0d85af4_0 --> pkgs/main::openssl-1.1.1k-h9ed2024_0


Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
--------------------------------------

That command updated ca-certificates and openssl.  I checked that the version of nodejs in Julia's Conda installation is greater than 12, and it is.

(base) perry@greenmosss-MacBook-Pro 3 % /Users/perry/.julia/conda/3/bin/conda list nodejs
# packages in environment at /Users/perry/opt/anaconda3:
#
# Name                    Version                   Build  Channel
nodejs                    12.4.0               h6de7cb9_0    conda-forge/label/cf202003

--------------------------------------------------------------

Unfortunately I got the same error messages as in the original post.

**Comment by travigd** [comment]
I'd recommend opening an issue with JuptyerLab directly then.

**Comment by jim2236** [comment]
Ok.  Thank you
