### ISSUE TITLE
WebIO support for Visual Studio Code

### ISSUE THREAD

**Issue by vchuravy** [JuliaGizmos/WebIO.jl#462]
Using the Jupyter extension in VSCode I get a:

> Unable to load WebIO. Please make sure WebIO works for your Jupyter client. For troubleshooting, please see the WebIO/IJulia documentation.

**Comment by bradcarman** [comment]
I see this issue as well.  I attempted to get WebIO to render in the Julia Extension Plot Pane by using 

```julia
Base.show(io::IO, m::MIME"juliavscode/html", x::Node) = print(io, WebIO.htmlstring(x))
```

Then, when displaying a node the plot pane opens with the message:

> WebIO not detected.

**Comment by travigd** [comment]
It's up to the VSCode extension to provide integration with WebIO (since otherwise there's no way WebIO can know how to communicate with the Julia process).

IJulia is the only "first class" integration that we provide.

**Comment by JobJob** [comment]
As a workaround I'd recommend using the Blink backend, with the added advantage that you get a new window that you can put in a separate monitor.

e.g.
```julia
using Blink: Window, body!
using Interact: @manipulate
using Plots: plot, plotlyjs
##

plotlyjs()
w = Window()
##

x = range(0, 6π; length=1000)
ui = @manipulate for i in 1:10
  plot(sin.(i .* x) .* cos.(i .* 2x))
end

body!(w, ui)
```
