### ISSUE TITLE
WebIO not detected

### ISSUE THREAD

**Issue by jeffmcgough** [JuliaGizmos/WebIO.jl#464]
Julia 1.6.1  in  Jupyter Lab 3.0.14 

I get the same error in the REPL and in JupyterLab.  I keep thinking I am just being stupid on this but I had this working last year.  Anyway, here is what I entered:

using Pkg
Pkg.add("WebIO")
using WebIO
WebIO.install_jupyter_labextension()

And I get as output:

Info: Using default Jupyter executable at `/home/jeff/anaconda3/bin/jupyter`; to use a different executable, see the documentation by running `?WebIO.install_jupyter_labextension`.
└ @ WebIO /home/jeff/.julia/packages/WebIO/Fy9h1/deps/jupyter.jl:198

An error occured.
ValueError: No linked package for @webio/webio
See the log file for details:  /tmp/jupyterlab-debug-797iaggs.log

No labextension named "@webio/jupyter-lab-provider" installed

An error occured.
ValueError: 
"@webio/jupyter-lab-provider@0.8.15" is not compatible with the current JupyterLab
Conflicting Dependencies:
JupyterLab              Extension      Package
>=3.0.9 <3.1.0          >=2.0.0 <3.0.0 @jupyterlab/application
>=3.0.9 <3.1.0          >=2.0.0 <3.0.0 @jupyterlab/docmanager
>=3.0.9 <3.1.0          >=2.0.0 <3.0.0 @jupyterlab/notebook
>=3.0.8 <3.1.0          >=2.0.0 <3.0.0 @jupyterlab/rendermime
>=6.0.7 <6.1.0          >=5.0.0 <6.0.0 @jupyterlab/services
See the log file for details:  /tmp/jupyterlab-debug-ki8in4f_.log

failed process: Process(`/home/jeff/anaconda3/bin/jupyter labextension install --no-build @webio/jupyter-lab-provider@0.8.15`, ProcessExited(1)) [1]

Stacktrace:
 [1] pipeline_error
   @ ./process.jl:525 [inlined]
 [2] run(::Cmd; wait::Bool)
   @ Base ./process.jl:440
 [3] run
   @ ./process.jl:438 [inlined]
 [4] install_jupyter_labextension(jupyter::Nothing; force_conda_jupyter::Nothing, condajl::Nothing, dev::Bool)
   @ WebIO ~/.julia/packages/WebIO/Fy9h1/deps/jupyter.jl:216
 [5] install_jupyter_labextension(jupyter::Nothing) (repeats 2 times)
   @ WebIO ~/.julia/packages/WebIO/Fy9h1/deps/jupyter.jl:196
 [6] top-level scope
   @ In[3]:4
 [7] eval
   @ ./boot.jl:360 [inlined]
 [8] include_string(mapexpr::typeof(REPL.softscope), mod::Module, code::String, filename::String)
   @ Base ./loading.jl:1094

**Comment by travigd** [comment]
Please upgrade to WebIO 0.8.16 (released today) and follow the instructions here: https://juliagizmos.github.io/WebIO.jl/latest/providers/ijulia/. Please follow up if you run into any issues or anything is unclear.

Thanks!

**Comment by jeffmcgough** [comment]
Awesome.  Thank you very much.

Jeff McGough
Computer Science and Engineering
South Dakota Mines
