### ISSUE TITLE
Integrate with HTTP.jl

### ISSUE THREAD

**Issue by EricForgy** [JuliaGizmos/WebIO.jl#47]
From Slack:

> Eric Forgy [3:15 PM]
> Maybe I can help adapt it to HTTP :blush:
>
> Shashi Gowda [3:19 PM]
> A PR for that would be welcome! 
> https://github.com/JuliaGizmos/WebIO.jl/blob/master/src/providers/mux_setup.jl is how I do it in Mux. WebIO integration also generally requires that package assets be available at `/pkg/`. `/pkg/Foo/bar.js` which corresponds to the file `Foo/assets/bar.js` in Foo.jl directory.
> GitHub
> JuliaGizmos/WebIO.jl
> WebIO.jl - a DSL for web-based widgets in Julia
> I ended up adding this directly to Mux -- https://github.com/JuliaWeb/Mux.jl/pull/34
> GitHub
> Serve package asset files by shashi · Pull Request #34 · JuliaWeb/Mux.jl
> A file at MyPkg/assets/js/test.js will be served at /pkg/MyPkg/js/test.js supersedes JunoLab/Blink.jl#55

```julia
using Mux
using WebIO
webio_serve(req -> TableView.showtable(t))
```

**Comment by shashi** [comment]
On second thought I think the concern of HTTP should not be HTML/CSS/JS.

**Comment by EricForgy** [comment]
My thought was / is that HTTP.jl now has a lot more functionality and can be a replacement for / alternative to Mux. Mux still uses HttpServer.jl which I think will / should be deprecated at some point. HTTP.jl also has its own implementation of WebSockets.

Plus, this gives me an excuse for me to finally look under the hood of this package 😊
