### ISSUE TITLE
`register_renderable` is not ideal

### ISSUE THREAD

**Issue by shashi** [JuliaGizmos/WebIO.jl#48]
I think the right way to go about this is to provide a trait:

```julia
WebIO.renderable(x::T) = true # and WebIO.renderable(x::Any) = false
```

Then the _backends_ are to be hooked up to always use `WebIO.render` when this trait is true.

Best way to do this is have backends depend on WebIO.

**Comment by travigd** [comment]
This is better now™. We have a `@register_renderable` macro and should only get better with the way that IJulia and things are moving.
