### ISSUE TITLE
Building package results in 404...

### ISSUE THREAD

**Issue by GlenHenshaw** [JuliaGizmos/WebIO.jl#486]
The package will not build due to a binary not being on the remote Julia package server.

        julia> versioninfo()
        Julia Version 1.7.2
        Commit bf53498635 (2022-02-06 15:21 UTC)
        Platform Info:
          OS: macOS (arm64-apple-darwin21.2.0)
          CPU: Apple M1
          WORD_SIZE: 64
          LIBM: libopenlibm
          LLVM: libLLVM-12.0.1 (ORCJIT, cyclone)

        julia> Pkg.status("WebIO")
              Status `~/.julia/environments/v1.7/Project.toml`
          [0f1e0344] WebIO v0.8.92

        julia> Pkg.build("WebIO")
            Building WebIO → `~/.julia/scratchspaces/44cfe95a-1eb2-52ea-b672-e2afdf69b78f/7564c65eeb3f31be72f6a3b54e1e929ccf040abd/build.log`
        ERROR: Error building `WebIO`:
        [ Info: Downloading WebIO core bundle from unpkg...
        ERROR: LoadError: HTTP/2 404 while requesting https://pkg.julialang.org/binary/WebIO.jl/v0.8.90/webio.bundle.js

...followed by a long stack trace which I don't think adds any additional insight. Note that the version of the binary attempting to be downloaded (0.8.90) does not match the version installed (0.8.92)

**Comment by travigd** [comment]
There is no version `0.8.90` or `0.8.92`. Are you using JuliaPro? I've seen errors like this when using that (not within our control).

**Comment by GlenHenshaw** [comment]
OK, I see the problem. My Julia general registry lists the following:

    0f1e0344-ec1d-5b48-a673-e5cf874b6c29 = { name = "WebIO", path = "W/WebIO" }

and if I go to W/WebIO I see:

    glenhenshaw@vpn202077 WebIO % more Package.toml
    name = "WebIO"
    uuid = "0f1e0344-ec1d-5b48-a673-e5cf874b6c29"
    repo = "https://github.com/bmharsha/WebIO.jl.git"

which is not you. It's a fork. *WHY* my registry is referencing a fork I have no idea. FWIW there's no version ''0.8.90'' or ''0.8.92'' of the fork either, but that's not your problem.

**Comment by travigd** [comment]
Sorry for the issues. Good luck! :)
