### ISSUE TITLE
setexcludinghandlers! was removed in Observables 0.5

### ISSUE THREAD

**Issue by rasmushenningsson** [JuliaGizmos/WebIO.jl#493]
With the compat update to support Observables 0.5, we get problems here
https://github.com/JuliaGizmos/WebIO.jl/blob/c818b1f57758a32bbafebea4fe16ed41192bd9ff/src/scope.jl#L352
since `setexcludinghandlers!` no longer exists.
I'm not sure what a proper fix is.

The easiest fix would probably be to just access the field directly, since the function was implemented like this in Observables.jl:
`setexcludinghandlers!(obs::AbstractObservable, val) = observe(obs).val = val`

**Comment by PetrKryslUCSD** [comment]
Is there some fix? PlotlyJS is practically unusable because of this error.

**Comment by mzaffalon** [comment]
@PetrKryslUCSD I pin `WebIO` to v0.8.17: `using Pkg; Pkg.add("WebIO"); Pkg.pin(name="WebIO", version="0.8.17")`.

**Comment by PetrKryslUCSD** [comment]
Excellent, that worked! Thanks!

**Comment by treygreer** [comment]
I have the same problem in Interact, and pinning WebIO to v0.8.17 doesn't work for me.

**Comment by rasmushenningsson** [comment]
bump :slightly_smiling_face:

**Comment by travigd** [comment]
Open to PRs here. Looks like this was a breaking change introduced to Observables.jl in https://github.com/JuliaGizmos/Observables.jl/pull/84/files#diff-717dd66a485f4523942145feb17dfcebc7bf9e137ee03fa29c1ef8c8c3b1cad6L272 (cc @SimonDanisch)

**Comment by rasmushenningsson** [comment]
I opened a PR in Observables (https://github.com/JuliaGizmos/Observables.jl/pull/97) to reintroduce the function instead.
If they don't want to reintroduce it, I'll open a PR with a local fix here.

**Comment by rcqls** [comment]
> I opened a PR in Observables ([JuliaGizmos/Observables.jl#97](https://github.com/JuliaGizmos/Observables.jl/pull/97)) to reintroduce the function instead. If they don't want to reintroduce it, I'll open a PR with a local fix here.

Why you don't do that. If you have a fix it could be a good point. I can't understand why PlotlyJS event handling is stuck because of this issue. That"s weird in the excellent Julia ecosystem.

**Comment by rasmushenningsson** [comment]
The PR in Observables was *just* merged, so no need for any action here.
