### ISSUE TITLE
Installation fails on Windows

### ISSUE THREAD

**Issue by vilim** [JuliaGizmos/WebIO.jl#53]
Thank you for developing this package!
However, I have problems installing it on windows: WebIO.devsetup() fails with the following:
`ERROR: could not spawn 'tar zvxf yarn.tar.gz -C .yarn': no such file or directory (ENOENT)`
Which is I guess expected given that tar is not installed in Windows.
However, a separately installed yarn, using the yarn install command in the assets/webio directory also gives an error, from the Windows Script Host:
Script: ...WebIO\assests\webio\node.js
Line: 253
Char: 29
Error: Expected identifier
Code: 800A03F2
Source: Microsoft JScript compilation error
 
Also, the modification of the jupyter_notebook_config.py does not take into account escaping of the windows path backslashes, which causes the script to fail.

**Comment by shashi** [comment]
Can you try now? We use NodeJS.jl now.

**Comment by shashi** [comment]
The instructions have changed. See README.

**Comment by vilim** [comment]
Thank you, all the examples from the README work now!

However I am unable to run the example with InteractNext (it seems that package and Vue.jl need to be updated to use JSExpr.jl, however even after importing them it still does not work).

**Comment by shashi** [comment]
Nice, I just updated Vue.jl, yet to update InteractNext.jl.

**Comment by shashi** [comment]
I think the core issue is solved here.
