### ISSUE TITLE
jupyter server doesn't work with large javascript assets

### ISSUE THREAD

**Issue by sglyon** [JuliaGizmos/WebIO.jl#57]
Trying to load `/pkg/PlotlyJS/plotly-latest.min.js` in jupyter errors.

In the terminal console (where I started jupyter) I see: 

```
[E 15:34:34.221 NotebookApp] Uncaught exception GET /pkg/PlotlyJS/plotly-latest.min.js (::1)
    HTTPServerRequest(protocol='http', host='localhost:8890', method='GET', uri='/pkg/PlotlyJS/plotly-latest.min.js', version='HTTP/1.1', remote_ip='::1', headers={'Host': 'localhost:8890', 'Connection': 'keep-alive', 'Upgrade-Insecure-Requests': '1', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8', 'Dnt': '1', 'Accept-Encoding': 'gzip, deflate, br', 'Accept-Language': 'en-US,en;q=0.9', 'Cookie': 'username-localhost-8888="2|1:0|10:1519331658|23:username-localhost-8888|44:NzRlNjU4NTY3ZWRlNGI4MmE3Y2IyMzlmMDM0N2FlMWI=|02d5a4d778974478c4349bf954cb877feeb1298f8e19e828ec39120fa7e1d696"; username-localhost-9271="2|1:0|10:1519670215|23:username-localhost-9271|44:ZDFkYzc4MWIzZDQ5NDkyOGJhMTkxYjc1YTI4YWFkZGQ=|eec64cf784e6e7b2cd8d362a5930e87823aa6a0482bf075eda7f63deea932400"; username-localhost-8890="2|1:0|10:1519857878|23:username-localhost-8890|44:YjFjOTNiN2YzYjkyNDMzNzg4NWM2ZDE0N2M4MGExOTI=|0d61933cd0232a5498984afcda76522224c18987a37c255d6c0f3f75bd0b9d4e"; _xsrf=2|e2288e49|b6e414a95688acfca1065dbd59450ce6|1519936253'})
    Traceback (most recent call last):
      File "/Users/sglyon/anaconda3/lib/python3.6/site-packages/tornado/web.py", line 1513, in _execute
        self.finish()
      File "/Users/sglyon/anaconda3/lib/python3.6/site-packages/tornado/web.py", line 992, in finish
        self.request.finish()
      File "/Users/sglyon/anaconda3/lib/python3.6/site-packages/tornado/httputil.py", line 419, in finish
        self.connection.finish()
      File "/Users/sglyon/anaconda3/lib/python3.6/site-packages/tornado/http1connection.py", line 448, in finish
        self._expected_content_remaining)
    tornado.httputil.HTTPOutputError: Tried to write 1554499 bytes less than Content-Length
[E 15:34:34.222 NotebookApp] Cannot send error response after headers written

```

In the javascript console of the browser I see

```
jquery.min.js:5 [Violation] Added synchronous DOM mutation listener to a 'DOMNodeInserted' event. Consider using MutationObserver to make the page more responsive.
add @ jquery.min.js:5
(anonymous) @ jquery.min.js:5
each @ jquery.min.js:4
each @ jquery.min.js:4
on @ jquery.min.js:5
KeyboardManager.register_events @ keyboardmanager.js:254
append_html @ outputarea.js:690
OutputArea.append_mime_type @ outputarea.js:671
OutputArea.append_execute_result @ outputarea.js:472
OutputArea.append_output @ outputarea.js:310
OutputArea.handle_output @ outputarea.js:243
output @ codecell.js:365
Kernel._handle_output_message @ kernel.js:1196
i @ jquery.min.js:4
Kernel._handle_iopub_message @ kernel.js:1223
Kernel._finish_ws_message @ kernel.js:1015
(anonymous) @ kernel.js:1006
VM93:2572 Uncaught (in promise) Error: Failed to fetch
  Instantiating http://localhost:8890/pkg/PlotlyJS/plotly-latest.min.js
  Loading /pkg/PlotlyJS/plotly-latest.min.js
t @ VM93:2572
(anonymous) @ VM93:2572
Promise.then (async)
createScope @ VM93:2903
createNode @ VM93:148
mount @ VM93:192
(anonymous) @ VM306:2
(anonymous) @ VM57:3003
evalInContext @ VM57:3003
proto.attachedCallback @ VM57:3011
(anonymous) @ jquery.min.js:5
domManip @ jquery.min.js:5
append @ jquery.min.js:5
OutputArea._safe_append @ outputarea.js:440
OutputArea.append_execute_result @ outputarea.js:476
OutputArea.append_output @ outputarea.js:310
OutputArea.handle_output @ outputarea.js:243
output @ codecell.js:365
Kernel._handle_output_message @ kernel.js:1196
i @ jquery.min.js:4
Kernel._handle_iopub_message @ kernel.js:1223
Kernel._finish_ws_message @ kernel.js:1015
(anonymous) @ kernel.js:1006
Promise.then (async)
Kernel._handle_ws_message @ kernel.js:1006
i @ jquery.min.js:4
VM93:2572 Uncaught (in promise) Error: Failed to fetch
  Instantiating http://localhost:8890/pkg/PlotlyJS/plotly-latest.min.js
  Loading /pkg/PlotlyJS/plotly-latest.min.js
```

**Comment by shashi** [comment]
:cry: I think IJulia sets this limit when you do `notebook()`, can you try `Conda/deps/usr/bin/jupyter notebook`?

**Comment by sglyon** [comment]
I started this jupyter from the command line (Not by calling the notebook function). 😟

**Comment by shashi** [comment]
Related: https://github.com/JuliaLang/IJulia.jl/issues/528 and https://github.com/JuliaLang/IJulia.jl/blob/397d190ae68c6d61425b0239733090cd93450875/deps/build.jl#L102

**Comment by sglyon** [comment]
I tried `jupyter notebook --NotebookApp.iopub_data_rate_limit=2147483647`, but that didn't help...

**Comment by shashi** [comment]
This is really unfortunate. Maybe if you downloaded PlotlyJS using npm you can do [code splitting](https://webpack.js.org/guides/code-splitting/).

**Comment by sglyon** [comment]
Thanks for the tip about code splitting. Because plotly.js updates frequently (every couple of weeks) I'd like to avoid solutions that don't allow me to just grab the latest `plotly-latest.min.js` and get to work.

Do you have any ideas why we are seeing this via the asset server while it hasn't come up in other settings?

**Comment by shashi** [comment]
I think I'm totally misunderstanding the problem here, I think it has nothing to do with what I pointed to above. It seems while writing the response,  something is setting a `Content-Length` header which doesn't simply match with the actual content's length.

I tried downloading https://cdn.plot.ly/plotly-latest.min.js into an assets directory to reproduce this issue, but I couldn't. It just worked. On Chrome+Linux.

**Comment by shashi** [comment]
The error could probably be traced starting from this line which prints the message in tornado python web framework -- https://github.com/tornadoweb/tornado/blob/master/tornado/http1connection.py#L451

**Comment by rdeits** [comment]
I'm getting the same error in Firefox on Ubuntu when loading the `WebIO` components javascript, which unfortunately makes WebIO unusable in jupyter lab. 

On `jupyter lab` startup, the server prints:

```
[E 19:39:20.968 LabApp] Uncaught exception GET /pkg/WebIO/webio/dist/webcomponents-lite.min.js (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:8838', method='GET', uri='/pkg/WebIO/webio/dist/webcomponents-lite.min.js', version='HTTP/1.1', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "/usr/local/lib/python3.5/dist-packages/tornado/web.py", line 1545, in _execute
        self.finish()
      File "/usr/local/lib/python3.5/dist-packages/tornado/web.py", line 1019, in finish
        self.request.finish()
      File "/usr/local/lib/python3.5/dist-packages/tornado/httputil.py", line 418, in finish
        self.connection.finish()
      File "/usr/local/lib/python3.5/dist-packages/tornado/http1connection.py", line 452, in finish
        self._expected_content_remaining)
    tornado.httputil.HTTPOutputError: Tried to write 19536 bytes less than Content-Length
```

and in the javascript console in my browser, I see: 

```
Loading failed for the <script> with source “http://localhost:8838/pkg/WebIO/webio/dist/webcomponents-lite.min.js”.
```

Visiting that URL on localhost shows that the contents of `webcomponents-lite.min.js` has been truncated to 2^16 characters. 

Switching to Chrome resolves the problem.

**Comment by rdeits** [comment]
More info: visiting the `/pkg/WebIO/webio/dist/webcomponents-lite.min.js` URL in Chrome still triggers the `HTTPOutputError` and results in an empty response in the browser. But, weirdly, WebIO.jl just works anyway in Chrome, with no errors. I'm baffled.

**Comment by shashi** [comment]
Chrome doesn't need webcompoments polyfill.. it shouldn't even be trying to load the file on chrome..... I think maybe I'm supposed to call some super class method in the tornado server plugin....


I'm unable to reproduce this locally, so will have to debug this through you two... 
https://stackoverflow.com/questions/28146700/writing-the-content-length-header-to-the-client-from-the-server-in-tornado?rq=1

Found this which talks about the error message.

In your case does it always say `19536 bytes less than Content-Length`

Or does the number change?

**Comment by rdeits** [comment]
Thanks for your help! Yes, it's always exactly the same message. Specifically, the length is exactly 19536 bytes which is exactly the number of bytes in that js file minus 2^16. The browser, likewise, always receives exactly the first 2^16 characters of the file.

**Comment by rdeits** [comment]
I was also wondering if there was some issue with a maximum length of a single line, but adding newlines throughout the file does not help.

**Comment by rdeits** [comment]
I'm starting to understand more of what's going on here, although I don't have a solution yet. What's happening under the hood is that WebIO's JuliaPackageAssetServer uses tornado's StaticFileHandler internally. The way StaticFileHandler works is by chunking files into 64kB blobs: https://github.com/tornadoweb/tornado/blob/b9e2da2046c521c8d71988f03307db36809282af/tornado/web.py#L2630 When serving the WebIO assets, however, only the first chunk is actually transmitted. That is, this loop, which should be iterating through all the chunks, only executes its first iteration: https://github.com/tornadoweb/tornado/blob/b9e2da2046c521c8d71988f03307db36809282af/tornado/web.py#L2472

I suspect this has something to do with the fact that `StaticFileServer.get()` is a coroutine, so perhaps `JuliaPackageAssetServer.get()` should also be a coroutine which yields from that coroutine?
