### ISSUE TITLE
jupyter server install

### ISSUE THREAD

**Issue by sglyon** [JuliaGizmos/WebIO.jl#58]
If a user has both `~/.jupyter/jupyter_notebook_config.py` and `~/.jupyter/jupyter_notebook_config.json` then the `c.NotebookApp.nbserver_extensions` section of the .py file will be ignored.

In that case we should have _both_ what you currently do and add `"jlstaticserve": true` to the json file so it looks something like

```
{
  "NotebookApp": {
    "nbserver_extensions": {
      "jupyter_nbextensions_configurator": true,
      "egal": true,
      "jlstaticserve": true
    }
  }
}

```

**Comment by shashi** [comment]
Good detective work :+1:

**Comment by shashi** [comment]
Hmm but I can't check to see to load it only if it exists... :( No way to run something in Pkg.rm.

**Comment by sglyon** [comment]
Sorry I didn't understand. What can't you check for?

**Comment by shashi** [comment]
Check to see if the plugin file exists... It may have been removed by a Pkg.rm -- we don't want Jupyter to throw errors for users in that case.

**Comment by sglyon** [comment]
I think it just issues a warning if a non-existent package is enabled in the json file.

Adding `"foobar": true` to the json file shows this when I start jupyter:

```
[W 08:19:26.319 NotebookApp] Error loading server extension foobar
    Traceback (most recent call last):
      File "/Users/sglyon/anaconda3/lib/python3.6/site-packages/notebook/notebookapp.py", line 1271, in init_server_extensions
        mod = importlib.import_module(modulename)
      File "/Users/sglyon/anaconda3/lib/python3.6/importlib/__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 994, in _gcd_import
      File "<frozen importlib._bootstrap>", line 971, in _find_and_load
      File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
    ModuleNotFoundError: No module named 'foobar'
```

**Comment by shashi** [comment]
Just curious, what is `egal: true`?

**Comment by sglyon** [comment]
Something I thought looked cool, but I never ended up using: https://github.com/uclmr/egal

**Comment by shashi** [comment]
That _is_ cool!
