### ISSUE TITLE
Way to include google fonts

### ISSUE THREAD

**Issue by djsegal** [JuliaGizmos/WebIO.jl#62]
Is there a way to add google fonts to a Scope through imports?

```
<link href="https://fonts.googleapis.com/css?family=Press+Start+2P" rel="stylesheet">
```

**Comment by shashi** [comment]
`Scope(imports=["https://fonts.googleapis.com/css?family=Press+Start+2P"])` should work?

**Comment by djsegal** [comment]
I get the following error :'(

<img width="1680" alt="screen shot 2018-03-09 at 12 42 44 pm" src="https://user-images.githubusercontent.com/3156114/37221306-777d4d0a-2397-11e8-9ae0-acb0f04723ff.png">
