### ISSUE TITLE
Way to invalidate assets (i.e. css)

### ISSUE THREAD

**Issue by djsegal** [JuliaGizmos/WebIO.jl#64]
If I have a `css` file in my `assets` folder it gets served correctly the first time.

But if I update the `css` file while I'm working on stuff, each call only finds the cached version.

Is there a way to delete the assets cache (for development)?

**Comment by shashi** [comment]
Ctrl+reload should usually do it (even in IJulia). But with your #62 fix, you can actually suffix `"?$(randstring(10))"` to the end of your CSS URL to trigger a reload every time :-)

**Comment by djsegal** [comment]
well played! thanks man

**Comment by djsegal** [comment]
Whoops. Actually, there is a build-up of the css files :(

<img width="630" alt="screen shot 2018-03-12 at 2 26 29 pm" src="https://user-images.githubusercontent.com/3156114/37302250-5fc3d58c-2601-11e8-924f-9e72b97e9fbd.png">

Is there a way to remove assets when the scope is no longer in use?

**Comment by shashi** [comment]
Good observation... I think we can do this if we spend the style to what is displayed rather than to `document.head`, since it will get removed when the Dom gets removed

**Comment by djsegal** [comment]
well played!
