### ISSUE TITLE
Way to host non-{html,css,js} assets

### ISSUE THREAD

**Issue by djsegal** [JuliaGizmos/WebIO.jl#65]
Let's say you have a `mp3` file in the `assets` directory.

------

Why does the following javascript:

```
var music = new Howl({
  src: ['pkg/<PkgName>/song.mp3'],
  autoplay: true,
  loop: true
});
```

cause the javascript console error

```javascript
GET http://localhost:8888/notebooks/pkg/<PkgName>/song.mp3 404 (Not Found)
```

-----

how do you get rid of the `/notebooks/` part of the url?

**Comment by djsegal** [comment]
current workaround is:

```
  cur_js = replace(
    string(JSString(cur_js)),
    "/notebooks/pkg/<PkgName>/",
    "/pkg/<PkgName>/"
  )
```

**Comment by shashi** [comment]
Try this:

```
src: ['/pkg/<PkgName>/song.mp3'],
```

The leading / should get the right file

**Comment by djsegal** [comment]
resolved! 

// there was just some funky stuff going on with the `howler.js` library too and i couldn't separate the two
