### ISSUE TITLE
No output in IJulia

### ISSUE THREAD

**Issue by cstjean** [JuliaGizmos/WebIO.jl#66]
Ubuntu, IJulia 1.7.0 and WebIO 1.5.0, I don't get anything in IJulia

![image](https://user-images.githubusercontent.com/8622776/37422713-37925d76-2792-11e8-8fdd-ea659631ce88.png)

Here's the JSON in the .ipynb file:

```julia
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div class='display:none'></div><unsafe-script style='display:none'>\n",
       "WebIO.mount(this.previousSibling,{&quot;props&quot;:{},&quot;nodeType&quot;:&quot;DOM&quot;,&quot;type&quot;:&quot;node&quot;,&quot;instanceArgs&quot;:{&quot;namespace&quot;:&quot;html&quot;,&quot;tag&quot;:&quot;div&quot;},&quot;children&quot;:[&quot;Hello, World&quot;]})</unsafe-script>"
      ],
      "text/plain": [
       "(div\n",
       "  \"Hello, World\")"
      ]
     },
     "execution_count": 2,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "Node(:div, \"Hello, World\")"
   ]
  }
 ],
```

I did `Pkg.build("WebIO")`. Also tried `devsetup(); bundlejs(); build("WebIO")`. All of that works without error, but it doesn't help even after restart.

**Comment by cstjean** [comment]
Working now. Not sure what I did, since I hit other issues in the mean time, but some combination of `conda update jupyter`, restarting the jupyter server, and using `http://0.0.0.0` instead of my ip address fixed the issue.

**Comment by shashi** [comment]
Something like this happened to me this morning... Will investigate if I can reproduce!
