### ISSUE TITLE
No home

### ISSUE THREAD

**Issue by SimonDanisch** [JuliaGizmos/WebIO.jl#67]
https://github.com/JuliaGizmos/WebIO.jl/blob/11389b75f0631d01dc3bcc924d8facc0e253309a/deps/build.jl#L6

This line assumes ENV["HOME"] is defined - which it isn't?! At least on windows it isn't ;)

**Comment by SimonDanisch** [comment]
I also get
```Julia
Test Summary: | Pass  Total
Blink mocks   |    1      1
ERROR: LoadError: LoadError: unlink: resource busy or locked (EBUSY)
```
Seems like this wasn't tested on windows, which needs stricter freeing of file handles

**Comment by pdeffebach** [comment]
I changed "HOME" to "HOMEPATH" and it worked.

**Comment by SimonDanisch** [comment]
I just opened a PR to use `homedir()`
