### ISSUE TITLE
Getting package to work in binder notebook (preliminary)

### ISSUE THREAD

**Issue by djsegal** [JuliaGizmos/WebIO.jl#68]
example binder project:

+ https://github.com/djsegal/webio-binder

corresponding binder:

+ http://35.192.139.11/v2/gh/djsegal/webio-binder/master

------

i tried to make the simplest binder package, but couldn't get webio to work on it.

could you take a look? don't know who to ask :(

------

![screen shot 2018-03-17 at 3 08 57 am](https://user-images.githubusercontent.com/3156114/37552702-8f71dde6-2990-11e8-81ea-143e38dae491.png)

**Comment by shashi** [comment]
So it needs a server plugin that can serve assets from `/pkg/` ... See https://github.com/JuliaGizmos/WebIO.jl/blob/master/deps/jlstaticserve.py

I guess the trick is getting it to install in binder

**Comment by shashi** [comment]
Looks fine as long as

`/srv/julia/pkg/v0.6/WebIO/assets/` is where julia packages are served from.

I guess the thing to check is whether binder is picking up the config file that `WebIO.build()` injects into.

Also it might have something to do with #58

**Comment by djsegal** [comment]
`/srv/julia/pkg/` is not on Julia's `LOAD_PATH`

currently looking into how to do this.

**Comment by djsegal** [comment]
@shashi what does it mean if the yarn.js install fails:

> `error webpack@4.1.1: The engine "node" is incompatible with this module. Expected version ">=6.11.5".`

------

![screen shot 2018-03-18 at 7 20 45 pm](https://user-images.githubusercontent.com/3156114/37572459-b2f46dcc-2ae1-11e8-8a25-5904b3ad5d28.png)

**Comment by djsegal** [comment]
It looks like `webpack@4.1.1` requires `nodejs@6.11.5`, but binder only has `nodejs@6.11.4`

Currently trying to resolve how to update nodejs

**Comment by shashi** [comment]
It seems like that webpack version needs a certain node version which does not exist on binder.

In the interest of making this work on many systems, I'm easy about which version of webpack we insist on as long as it is able to successfully build the files we need.

However I would have thought WebIO would use the `node` binary installed by NodeJS.jl. Is that not the case?

**Comment by djsegal** [comment]
`NodeJS.jl` is not `REQUIRE`d by `WebIO.jl`

That will be the next thing I try out

**Comment by shashi** [comment]
Actually to install server plugin one just needs to run build.

You're trying a Dev install which is strictly not needed

**Comment by djsegal** [comment]
I'm pretty sure it says that web_comm doesn't exist then

// let me try in a couple hours
