### ISSUE TITLE
RFH: Making Javascript package management even more painless

### ISSUE THREAD

**Issue by shashi** [JuliaGizmos/WebIO.jl#7]
Right now [`WebIO.devsetup()` and `WebIO.bundlejs()`](https://github.com/shashi/WebIO.jl/blob/master/src/devsetup.jl) works on Linux if nodejs is installed.

I would wager it works on Mac as well if nodejs is installed (would be great if someone can confirm this!)

Hopefully it will be possible to get this working on Windows in a self-contained way. (see https://yarnpkg.com/docs/install for more info)

Work items:

On Linux and Mac
- [x] Check to see if node is installed and try to install it if not in user space

On Windows
- [x] Get devsetup to work on Windows albeit with more steps
- [x] Document this

**Comment by rohitvarkey** [comment]
@shashi On running `WebIO.devsetup()` I got a

```
yarn install v0.19.1
info No lockfile found.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error webpack@2.2.1: The engine "node" is incompatible with this module. Expected version ">=4.3.0 <5.0.0 || >=5.10".
error Found incompatible module
```

I followed the suggestion at https://github.com/gilbarbara/react-joyride/issues/131 to use `yarn --ignore-engines` and it worked fine then. Maybe add this also as part of the `devsetup` commands?

Once this worked, `bundlejs` worked fine. 

```julia
julia> WebIO.bundlejs()
Hash: 804b8d7066a2b81ec897
Version: webpack 2.2.1
Time: 123ms
          Asset     Size  Chunks             Chunk Names
webio.bundle.js  11.5 kB       0  [emitted]  WebIO
   [0] ./basics/webio.js 3.03 kB {0} [built]
   [1] ./basics/node.js 5.71 kB {0} [built]
   [2] ./index.js 74 bytes {0} [built]
```

**Comment by shashi** [comment]
Are you on a Mac?

Any idea what this option does?

**Comment by rohitvarkey** [comment]
> Are you on a Mac?

Yes.

> Any idea what this option does?

I think its something to do with `npm` and `yarn` having inconsistencies with each other. 

```$ node --version
v5.4.1
```

Even though I have the expected version, it doesn't install.

**Comment by shashi** [comment]
Seems like it's only safe to use `--ignore-engines` if you aren't going to use the package with node... But we will be using webpack. So the right solution is to probably upgrade `node`. Do you know how you installed node?

It's probably best to automatically download and install node right here and use that binary to run yarn... I don't know how hard that would be?

**Comment by JobJob** [comment]
You can install node on mac with Brew: https://github.com/JuliaPackaging/Homebrew.jl

**Comment by shashi** [comment]
Yeah I think we need a way to get a local node install for reliability. Also on travis the pre installed node version is too old for yarn, so we'll either need that or use https://blog.travis-ci.com/2016-11-21-travis-ci-now-supports-yarn

**Comment by davidanthoff** [comment]
Maybe https://github.com/davidanthoff/NodeJS.jl would help here?

**Comment by shashi** [comment]
Thanks @davidanthoff NodeJS.jl works great! :-)

**Comment by davidanthoff** [comment]
At some point we could extend NodeJS.jl it to host node in-process. I think the node folks have been working on the ability to created a shared library version of node, and at that point it might become feasible.

**Comment by NV1028** [comment]
came here from https://github.com/gilbarbara/react-joyride/issues/131

no suggestions fixed my issue yet
