### ISSUE TITLE
Get Binder working across all browsers

### ISSUE THREAD

**Issue by djsegal** [JuliaGizmos/WebIO.jl#72]
Continuation of issue https://github.com/JuliaGizmos/WebIO.jl/issues/68 // was just too cluttered

Scenario now is:

> I have a binder that serves assets, but can't correctly find them

-------

i.e.

website looks for assets at:
+ http://example.com/hub/pkg/WebIO/webio/dist/bundle.js?_=1521526313580

but if you hunt around with chrome, you find they're actually at:
+ http://example.com/user/djsegal-webio-binder-o0v60382/pkg/WebIO/webio/dist/bundle.js?_=1521526313580

and this is because the user is at the jupyter notebook: 
+ http://example.com/user/djsegal-webio-binder-o0v60382/notebooks/julia.ipynb

-----

What part of the code do you think is responsible for this?

**Comment by djsegal** [comment]
@shashi, is it related to: 

https://github.com/JuliaGizmos/WebIO.jl/blob/4807fc33dd46a115183d507894a4bbe8d5e6b37e/deps/jlstaticserve.py#L37-L39

Just trying to get my bearings before I setup a development environment for webio

**Comment by shashi** [comment]
Unfortunately I think this is a `<base>` setting being done outside of WebIO https://www.w3schools.com/tags/tag_base.asp

I'm all ears if there are workarounds!

**Comment by djsegal** [comment]
I've started with some workarounds:

+ https://github.com/djsegal/WebIO.jl/commit/102359a7ab201d17f4cd04d4f03fd81771c47cec

Another might be something a la:

+ https://discourse.julialang.org/t/how-to-get-url-of-current-jupyter-notebook/9851

**Comment by shashi** [comment]
Can we close this now?

**Comment by djsegal** [comment]
Closing :)
