### ISSUE TITLE
IJulia connection does not survive page reload

### ISSUE THREAD

**Issue by cstjean** [JuliaGizmos/WebIO.jl#85]
For instance, if I execute

```julia
using WebIO, JSExpr

function random_print_button()
    w = Scope()

    obs = Observable(w, "rand-value", 0.0)

    on(obs) do x
        println("JS sent $x")
    end

    w(
      dom"button"(
        "generate random",
        events=Dict("click"=>@js () -> $obs[] = Math.random()),
      ),
    )
end

random_print_button()
```

then it works, but after refreshing the page, the button doesn't do anything anymore. And if I reexecute the cell, then I get no button/output at all.

**Comment by shashi** [comment]
There are two issues:

1. Reloading clears the observables metadata used in the page. -- This should be relatively easy to fix.
2. If you run `using WebIO` twice in IJulia, it actually removes the WebIO base JavaScript because running `using WebIO` a second time doesn't print the JS (since `__init__` will not be called), this is why you can't even render anything after the reload.

**Comment by cstjean** [comment]
If I've reloaded the page, is there anything I can execute to "reset" WebIO, short of restarting my julia session?

**Comment by rdeits** [comment]
Does `WebIO.setup(:ijulia)` work?

**Comment by shashi** [comment]
Now it does. :)

**Comment by shashi** [comment]
Ah well only on JupyterLab.

**Comment by travigd** [comment]
There are two issues here. The refresh survives a reload now using `WebIO#master`. In Jupyter Notebook (I'm not sure about lab), the part that doesn't work is `println`. When the page is refreshed, no cell is marked as "active" and so, essentially, all stdout is ignored. To see this, consider this.
```julia
@async begin
    for i in 1:50
        println(i)
    end
end
```

It will work as expected. Try refreshing. Nothing should be printing any more.

Create a new cell and run
```julia
println("foo")
```

The output should then be continued in the output area of that cell. If you want it to work, you'd have to change the println to update something on the page. **This** works (and will continue to work across page reloads).

```julia
using WebIO, JSExpr

function random_print_button()
    w = Scope()

    obs = Observable(w, "rand-value", 0.0)

    onjs(obs, @js function(x)
        this.dom.querySelector(".output").innerHTML = x
    end)

    w(
        dom"div"(
            dom"button"(
                "generate random",
                events=Dict("click"=>@js () -> $obs[] = Math.random()),
            ),
            dom"pre.output"(""),
        ),
    )
end

random_print_button()
```

Note that that can actually be simplified to 
```julia
using WebIO, JSExpr

function random_print_button()
    w = Scope()

    obs = Observable(w, "rand-value", 0.0)

    w(
        dom"div"(
            dom"button"(
                "generate random",
                events=Dict("click"=>@js () -> $obs[] = Math.random()),
            ),
            dom"pre.output"(obs),
        ),
    )
end

random_print_button()
```
and WebIO will handle the actual updating for you.

**Comment by shashi** [comment]
Still, pretty awesome!
