### ISSUE TITLE
Add some flair to the "setting up" print message

### ISSUE THREAD

**Issue by djsegal** [JuliaGizmos/WebIO.jl#87]
Nitpick of the century, but could we make the following line a little cooler? 😛 

```julia
WebIO: setting up ijulia
```
+ https://github.com/JuliaGizmos/WebIO.jl/blob/bd90aa4d777061335782c63b2c201acfe60cc64b/src/WebIO.jl#L28

-------

One thing, I've been doing is removing it after load:

```julia
cur_script = """
  <script class="js-load-remove-tag">
    \$('pre:contains("WebIO: setting up")').parent(".output_subarea").remove();
    \$(".js-load-remove-tag").parent(".output_subarea").remove();
  </script>
"""

display(HTML(cur_script))
```

**Comment by shashi** [comment]
cc @JobJob

**Comment by JobJob** [comment]
Lolz @ removing it in js. 
It's mostly for debugging. Could be removed. Maybe could change it to 
```
haskey(ENV, "WEBIO_DEBUG") && println("WebIO: setting up $provider") 
```
(n.b. ENV["key"] is always a string)

**Comment by djsegal** [comment]
This was resolved. Closing
