### ISSUE TITLE
Way to view javascript calls in developer console

### ISSUE THREAD

**Issue by djsegal** [JuliaGizmos/WebIO.jl#91]
I can't seem to find any javascript calls being made. Is there a way to view them in the developer console?

This would help in tracking down api-throttling bugs :bug:

**Comment by shashi** [comment]
You can `console.log` all messages here https://github.com/JuliaGizmos/WebIO.jl/blob/master/assets/webio/webio.js#L69 would be nice to have a flag that toggles the logging.

**Comment by djsegal** [comment]
This is a nice to have. Closing
