### ISSUE TITLE
Signal with scope cannot contain other values

### ISSUE THREAD

**Issue by cstjean** [JuliaGizmos/WebIO.jl#93]
I'm putting a scope inside a signal to get reactive updating of my PlotlyWebIO plots via `push!`. This works great, aside from the nagging feeling that I'm using this technology all wrong. In any case, I bumped today into this error:
![image](https://user-images.githubusercontent.com/8622776/38691778-cad1b5ea-3e4f-11e8-8d7c-dd41f83e0344.png)

Pushing a string into that signal triggers that warning, and fails to update the `Out[23]` value. Shouldn't that work? It looks like the value I pushed is somehow translated into a MIME type.

**Comment by shashi** [comment]
> This works great, aside from the nagging feeling that I'm using this technology all wrong.

:sweat_smile: 

> I'm putting a scope inside a signal to get reactive updating of my PlotlyWebIO plots via push!. 

while this will work on IJulia, it will not work on anything else. Also not how it was probably intended to be used :)

2 options:

1. Have plot update via Scope itself.... i.e. just listen to observable(s) within the scope to update whatever is required.
2. use an Observable of scopes... You will have to call `WebIO.render(obs_scope)` on the observable of scopes to render it reactively...

Would be good to understand your use case better... Why can't 1) work?

**Comment by cstjean** [comment]
> use an Observable of scopes... You will have to call WebIO.render(obs_scope) on the observable of scopes to render it reactively...

Thank you, I'll try that!

> Have plot update via Scope itself.... i.e. just listen to observable(s) within the scope to update whatever is required.

I'm sure that would work, but in general, it is more work to write `plot(state)` and `update!(state_diff)` than just `plot(new_state)`. At least, in my case it is. I have a long vector containing labels like `v = ["Good", "Good", "Good", "Bad", "Bad", "Chaotic", "Good", "Good"]` for corresponding dates. For each sequence of `Good` (eg. `v[1:3]`, I plot a red line. For each `Bad`, I plot a green line, etc. The label vector changes, but I don't see how I could set up a reactive pipeline, especially since at the end of it I need to work with plotly's `addtrace` and `removetrace`. 

I'm new to reactive programming, so maybe I'm missing something!

**Comment by travigd** [comment]
Closing because this issue is based on an old version of WebIO.
