### ISSUE TITLE
WebIO breaks IJulia gifs

### ISSUE THREAD

**Issue by cstjean** [JuliaGizmos/WebIO.jl#95]
If I run this in IJulia, Julia 0.6, Linux, I get a "broken link" image, but if I remove `using WebIO`, it works fine. Can anyone reproduce? I'm trying to create a MWE, but there's a lot of ground to cover...

```julia
using WebIO
using Plots

gr()
@gif for i in 1:10
    plot(randn(10))
    end
```

**Comment by cstjean** [comment]
MWE:

1. Download a gif from the web. Eg. `wget https://upload.wikimedia.org/wikipedia/commons/a/aa/SmallFullColourGIF.gif`
2. Run `HTML("<img src=\"SmallFullColourGIF.gif?>\" />")` in a notebook cell. Wonder at full-color gifs.
3. `using WebIO`
4. Rerun the HTML cell from above. Wonder no more.

**Comment by travigd** [comment]
This seems to have been fixed over the millennia that have passed since this bug was filed. I'm going to close it.
